import type { PixelIconId } from '@shared/pixel-icon';

/** A 16x16 pixel icon: one char per pixel, '.' is transparent, every other char is a palette key. */
export interface PixelIconDef {
  readonly palette: Readonly<Record<string, string>>;
  readonly rows: readonly string[];
}

// Palette: the UI tokens (src/styles/tokens.css) plus the darker/lighter shades the art needs.
const INK: string = '#0e0d0b';
const INK_2: string = '#1b1916';
const WHITE: string = '#fff8e8';
const BONE: string = '#e8dcc2';
const BONE_DIM: string = '#a89c84';
const BONE_FAINT: string = '#6f6656';
const BLOOD_HI: string = '#e0503f';
const BLOOD: string = '#b8322a';
const BLOOD_DARK: string = '#6e1c17';
const HP_HI: string = '#ef5a46';
const HP: string = '#c9302c';
const RUST_HI: string = '#e8964a';
const RUST: string = '#c9762c';
const RUST_DARK: string = '#7a4318';
const GLOW: string = '#fff3b0';
const GOLD_HI: string = '#ffe08a';
const GOLD: string = '#f2c14e';
const GOLD_DARK: string = '#b07f22';
const TOXIC_HI: string = '#b5e05a';
const TOXIC: string = '#8fbf3a';
const TOXIC_DARK: string = '#557a22';
const STEEL_LIGHT: string = '#a9bac6';
const STEEL_HI: string = '#6f8190';
const STEEL: string = '#4f5d68';
const STEEL_DARK: string = '#2e363d';
const MP_HI: string = '#5f9bef';
const MP: string = '#3a74c9';
const MP_DARK: string = '#1f4580';
const PURPLE_HI: string = '#c48ce8';
const PURPLE: string = '#8a4fc0';
const PURPLE_DARK: string = '#55307a';
const TEAL_HI: string = '#8fe8d8';
const TEAL: string = '#3fb3a0';
const TEAL_DARK: string = '#1f6e62';
const WOOD_HI: string = '#b07a44';
const WOOD: string = '#8a5a2e';
const WOOD_DARK: string = '#5e3d20';
const PINK_HI: string = '#f4b4b8';
const PINK: string = '#d87c88';
const PINK_DARK: string = '#8e4452';

/** Small round potion bottle; liquid l/m/d, glass c/s, cork h/H. */
const POTION_SMALL_ROWS: readonly string[] = [
  '................',
  '................',
  '................',
  '.......kk.......',
  '......khHk......',
  '.....kcccsk.....',
  '.....kkcsk......',
  '....kwlllmkk....',
  '...klwllmmmdk...',
  '...klwllmmmdk...',
  '...kllmmmmddk...',
  '...klmmmmmddk...',
  '....kmmmmddk....',
  '.....kddddk.....',
  '......kkkk......',
  '................',
];

/** Medium potion bottle; same letters as the small one. */
const POTION_MEDIUM_ROWS: readonly string[] = [
  '................',
  '......kkkk......',
  '.....khhHHk.....',
  '.....khHHHk.....',
  '....kccccssk....',
  '.....kccssk.....',
  '....kllllmmk....',
  '...klwllllmmk...',
  '..klwwlllmmmdk..',
  '..klwlllmmmmdk..',
  '..klllmmmmmddk..',
  '..kllmmmmmdddk..',
  '..klmmmmmddddk..',
  '...kmmmmmdddk...',
  '....kddddddk....',
  '.....kkkkkk.....',
];

/** Large potion jug with a label band; same letters as the small one. */
const POTION_LARGE_ROWS: readonly string[] = [
  '.....kkkkk......',
  '....khhhHHk.....',
  '....khHHHHkk....',
  '...kccccccssk...',
  '....kccccssk....',
  '...klllllmmmk...',
  '..klwwllllmmmk..',
  '.klwwllllmmmmdk.',
  '.klwlllllmmmmdk.',
  '.kbbbbbbbbbbBBk.',
  '.kBBBBBBBBBBffk.',
  '.kllmmmmmmmdddk.',
  '.klmmmmmmmddddk.',
  '..kmmmmmmmdddk..',
  '...kddddddddk...',
  '....kkkkkkkk....',
];

/** Hand-drawn icon set. 'k' is the 1px ink outline in every palette. */
export const PIXEL_ICONS: Readonly<Record<PixelIconId, PixelIconDef>> = {
  sword: {
    palette: {
      k: INK,
      w: WHITE,
      c: STEEL_LIGHT,
      S: STEEL,
      y: GOLD_HI,
      g: GOLD,
      G: GOLD_DARK,
      h: WOOD_HI,
      H: WOOD,
    },
    rows: [
      '............kk..',
      '...........kwck.',
      '..........kwcSk.',
      '.........kwcSk..',
      '........kwcSk...',
      '..kk...kwcSk....',
      '.kygk.kwcSk.....',
      '..kygkwcSk......',
      '...kgwcSk.......',
      '....kgGk........',
      '...khHgGk.......',
      '..khHkkGGk......',
      '.kygk..kk.......',
      '.kgGk...........',
      '..kk............',
      '................',
    ],
  },
  bow: {
    palette: { k: INK, h: WOOD_HI, H: WOOD, b: BONE, c: STEEL_LIGHT, R: BLOOD_HI, w: WHITE },
    rows: [
      '.........kk.....',
      '........khHb....',
      '.......khHkb....',
      '......khHk.b....',
      '.....khHk..b....',
      '..k.khHk...bkk..',
      '.kckhHk....bRRk.',
      'kwcbbbbbbbbbRRk.',
      '.kckhHk....bRRk.',
      '..kkhHk....bkk..',
      '....khHk...b....',
      '.....khHk..b....',
      '......khHk.b....',
      '.......khHkb....',
      '........khHb....',
      '.........kk.....',
    ],
  },
  orb: {
    palette: {
      k: INK,
      u: PURPLE_HI,
      U: PURPLE,
      w: WHITE,
      m: PURPLE_DARK,
      y: GOLD_HI,
      g: GOLD,
      G: GOLD_DARK,
    },
    rows: [
      '.....kkkkkk.....',
      '....kuuuuUUk....',
      '...kuwwuuUUUk...',
      '..kuwwuuUUUUUk..',
      '..kuwuuUUUUUmk..',
      '..kuuUUUUUUUmk..',
      '..kuUUUUUUUmmk..',
      '..kUUUUUUUUmmk..',
      '..kUUUUUUUmmmk..',
      '...kUUUUUmmmk...',
      '....kmmmmmmk....',
      '.....kkkkkk.....',
      '....kyggGGkk....',
      '...kyggggGGGk...',
      '..kGGGGGGGGGGk..',
      '...kkkkkkkkkk...',
    ],
  },
  dagger: {
    palette: {
      k: INK,
      c: STEEL_LIGHT,
      S: STEEL,
      w: WHITE,
      g: GOLD,
      G: GOLD_DARK,
      y: GOLD_HI,
      h: WOOD_HI,
      H: WOOD,
    },
    rows: [
      '.......kk.......',
      '......kcSk......',
      '......kwSk......',
      '......kwSk......',
      '......kcSk......',
      '......kcSk......',
      '......kcSk......',
      '...k..kcSk..k...',
      '..kgkkkcSkkkGk..',
      '..kyggggggggGk..',
      '...kkkkhHkkkk...',
      '......khHk......',
      '......khHk......',
      '.....kygGGk.....',
      '......kkkk......',
      '................',
    ],
  },
  holy: {
    palette: { k: INK, Y: GLOW, y: GOLD_HI, g: GOLD, w: WHITE, G: GOLD_DARK },
    rows: [
      '.......kk.......',
      '..Y...kygk...Y..',
      '...Y..kygk..Y...',
      '...kkkkygkkkk...',
      '..kyyyywyyyygk..',
      '..kggggygGGGGk..',
      '...kkkkygkkkk...',
      '......kgGk......',
      '...Y..kgGk..Y...',
      '..Y...kgGk...Y..',
      '......kgGk......',
      '......kgGk......',
      '......kgGk......',
      '......kGGk......',
      '.......kk.......',
      '................',
    ],
  },
  whirl: {
    palette: { k: INK, e: TEAL_HI, E: TEAL, F: TEAL_DARK },
    rows: [
      '......kkkkk.....',
      '....kkeeeeekk...',
      '...keeeeeeeEEk..',
      '..keeeekkkeEEEk.',
      '..keekkkekkkEEFk',
      '.keeekeeeEEkkFFk',
      '.keekeeeeEEFkFFk',
      '.keekeekkkFFkFFF',
      '.keekeeEkkFFkkkk',
      '.keeekEFFkFFk...',
      '..keEEkkkFFFk...',
      '..kEEEFFFFFk....',
      '...kkFFFFFk.....',
      '.....kkkkk......',
      '................',
      '................',
    ],
  },
  wind: {
    palette: { k: INK, c: STEEL_LIGHT, w: WHITE },
    rows: [
      '..........kkk...',
      '.........kccck..',
      '........kckkkck.',
      '.kkkkkkkkkkkkck.',
      'kwwwwwwwwwwwcck.',
      '.kkkkkkkkkkkkk..',
      '...kkkkkkkkkkkk.',
      '..kwwwwwwwwwwwwk',
      '...kkkkkkkkkkkk.',
      '.kkkkkkkkkkkk...',
      'kwwwwwwwwwwcck..',
      '.kkkkkkkkkkkck..',
      '.......kckkkck..',
      '........kccck...',
      '.........kkk....',
      '................',
    ],
  },
  heal: {
    palette: { k: INK, t: TOXIC_HI, T: TOXIC, w: WHITE, v: TOXIC_DARK },
    rows: [
      '................',
      '................',
      '...kkk....kkk...',
      '..ktttk..kTTTk..',
      '.ktwwtTkkTTTTvk.',
      '.ktwtTTTTTTTTvk.',
      '.kttTTTTTTTTTvk.',
      '.ktTTTTTTTTTvvk.',
      '..kTTTTTTTTvvk..',
      '...kTTTTTTvvk...',
      '....kTTTTvvk....',
      '.....kTTvvk.....',
      '......kvvk......',
      '.......kk.......',
      '................',
      '................',
    ],
  },
  shield: {
    palette: {
      k: INK,
      c: STEEL_LIGHT,
      r: BLOOD_HI,
      R: BLOOD,
      S: STEEL,
      y: GOLD_HI,
      g: GOLD,
      G: GOLD_DARK,
    },
    rows: [
      '..kkkkkkkkkkkk..',
      '.kcccccccccccck.',
      '.kcrrrrrRRRRRSk.',
      '.kcrrrrrRRRRRSk.',
      '.kcrrrrrRRRRRSk.',
      '.kcrrrrygRRRRSk.',
      '.kcrrrrgGRRRRSk.',
      '.kcrrrrrRRRRRSk.',
      '.kcrrrrrRRRRRSk.',
      '..kcrrrrRRRRSk..',
      '..kcrrrrRRRRSk..',
      '...kcrrrRRRSk...',
      '....kcrrRRSk....',
      '.....kcrRSk.....',
      '......kSSk......',
      '.......kk.......',
    ],
  },
  fist: {
    palette: { k: INK, b: BONE, B: BONE_DIM, f: BONE_FAINT, R: BLOOD, r: BLOOD_HI, q: BLOOD_DARK },
    rows: [
      '................',
      '...kk.kk.kk.kk..',
      '..kbBkbBkbBkbBk.',
      '..kbBkbBkbBkbBk.',
      '..kbBkbBkbBkbBk.',
      '.kbbbbbbbbkBBfk.',
      '.kbBBBBBBBkBBfk.',
      '.kBkkkkkkkBBBfk.',
      '.kBBBBBBBBBBBfk.',
      '..kBBBBBBBBBfk..',
      '...kRRRRRRRRk...',
      '...krRRRRRRqk...',
      '...krRRRRRRqk...',
      '...krRRRRRRqk...',
      '....kkkkkkkk....',
      '................',
    ],
  },
  magnet: {
    palette: {
      k: INK,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      r: BLOOD_HI,
      w: WHITE,
      R: BLOOD,
      q: BLOOD_DARK,
    },
    rows: [
      '..kkkk....kkkk..',
      '.kcccck..kcccck.',
      '.kcsssk..kcsssk.',
      '.kkkkkk..kkkkkk.',
      '.krwRRk..krRRRk.',
      '.krRRRk..krRRRk.',
      '.krRRRk..krRRRk.',
      '.krRRRk..krRRqk.',
      '.krRRRRkkRRRRqk.',
      '.krRRRRRRRRRRqk.',
      '..kRRRRRRRRRqk..',
      '...kqRRRRRRqk...',
      '....kkqqqqkk....',
      '......kkkk......',
      '................',
      '................',
    ],
  },
  dragon: {
    palette: { k: INK, b: BONE, B: BONE_DIM, r: BLOOD_HI, R: BLOOD, g: GOLD, q: BLOOD_DARK },
    rows: [
      '...k............',
      '..kbk...........',
      '..kBbk.kkk......',
      '...kBbkrrrkk....',
      '....kBrrrrRrkkk.',
      '...krrrrrrrRRRrk',
      '..krrrgkrrRRRRRk',
      '..krRRRRRRRRRRqk',
      '.krRRRRqqqqqqqqk',
      '.kRRRRbkbkbkbkk.',
      '.kRRRRkbkbkbk...',
      '.kRRRRqqqqqqk...',
      '.kqRRRqqqkkk....',
      '..kqRRqkk.......',
      '..kqqqk.........',
      '...kkk..........',
    ],
  },
  flask: {
    palette: {
      k: INK,
      c: STEEL_LIGHT,
      w: WHITE,
      s: STEEL_HI,
      t: TOXIC_HI,
      T: TOXIC,
      v: TOXIC_DARK,
    },
    rows: [
      '.....kkkkkk.....',
      '....kcccccck....',
      '.....kcwssk.....',
      '.....kcwssk.....',
      '.....kcwssk.....',
      '....kcttTTsk....',
      '....kctTTTsk....',
      '...kcttTTTTsk...',
      '...kctwTTTTsk...',
      '..kcttTTTTTTsk..',
      '..kctTTTwTTvsk..',
      '.kcttTTTTTTvvsk.',
      '.kctTTTTTTvvvsk.',
      '..kssssssssssk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  star: {
    palette: { k: INK, y: GOLD_HI, g: GOLD, w: WHITE, G: GOLD_DARK },
    rows: [
      '.......kk.......',
      '......kygk......',
      '......kygk......',
      '.....kyyggk.....',
      '.kkkkkyyggkkkkk.',
      'kyyyyyywgggggGGk',
      '.kyyyyyygggggGk.',
      '..kyyyyygggGGk..',
      '...kyyyyggGGk...',
      '...kyyyggGGGk...',
      '..kyyygGGgGGGk..',
      '..kyyGGkkgGGGk..',
      '.kyGGkk..kkGGGk.',
      '.kGGk......kGGk.',
      '..kk........kk..',
      '................',
    ],
  },
  spring: {
    palette: { k: INK, y: GOLD_HI, G: GOLD_DARK, c: STEEL_LIGHT, s: STEEL_HI, z: STEEL_DARK },
    rows: [
      '..kkkkkkkkkkkk..',
      '.kyyyyyyyyyyyGk.',
      '.kGGGGGGGGGGGGk.',
      '..kkcccccccckk..',
      '....kkkkkkcsk...',
      '...kssssssssk...',
      '..kcskkkkkkk....',
      '...kcccccccck...',
      '....kkkkkkcsk...',
      '...kssssssssk...',
      '..kcskkkkkkk....',
      '...kcccccccck...',
      '...kkkkkkkcsk...',
      '..kzzzzzzzzzzk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  paw: {
    palette: { k: INK, b: BONE, B: BONE_DIM },
    rows: [
      '....kk....kk....',
      '...kbbk..kbbk...',
      '..kbbbBkkbbbBk..',
      '..kbBBBkkbBBBk..',
      '.kkkBBk..kBBkkk.',
      'kbbkkk....kkkbbk',
      'kbbBk......kbbBk',
      'kbBBk.kkkk.kbBBk',
      '.kBk.kbbbbkkkBk.',
      '..k.kbbbbbbBkk..',
      '...kbbbbbbbBBk..',
      '...kbbbbbbBBBk..',
      '...kbbBBBBBBBk..',
      '....kBBBBBBBk...',
      '.....kBBkkBBk...',
      '......kk..kk....',
    ],
  },
  twins: {
    palette: { k: INK, s: STEEL_HI, S: STEEL, z: STEEL_DARK, w: WHITE, c: STEEL_LIGHT },
    rows: [
      '.........kkkk...',
      '........ksssSk..',
      '.......ksSSSSSk.',
      '.......ksSSSSzk.',
      '...kkkkkSSSSSzk.',
      '..kwwwckkSzzzk..',
      '.kwccccckkkkkk..',
      '.kwccccskssssSk.',
      '.kcccccskSSSSSSk',
      '..kcssskSSSSSSzk',
      '..kkkkkkzzzzzzzk',
      '.kwwwwwckkkkkkk.',
      'kwccccccck......',
      'kwccccccsk......',
      'kcsssssssk......',
      '.kkkkkkkk.......',
    ],
  },
  eclipse: {
    palette: { k: INK, j: GOLD, Y: GLOW, y: GOLD_HI, m: PURPLE_DARK, g: GOLD, U: PURPLE },
    rows: [
      '.......jj.......',
      '......kjjk......',
      '....kkYYYYkk....',
      '...jYYYYYYYyj...',
      '..kYYmmmmmmyyk..',
      '..kYmmmmmmmmyk..',
      '.kYYmmmmmmmmggk.',
      'jjYYmmmmmmmmggjj',
      'jjYYmmmmmmmUggjj',
      '.kYYmmmmmmmUggk.',
      '..kYmmmmmmUUgk..',
      '..kyymmmUUUggk..',
      '...jyyggggggj...',
      '....kkggggkk....',
      '......kjjk......',
      '.......jj.......',
    ],
  },
  moon: {
    palette: { k: INK, g: GOLD, Y: GLOW, y: GOLD_HI, G: GOLD_DARK },
    rows: [
      '................',
      '.....kk.........',
      '...kkggk........',
      '..kYYgk.........',
      '..kYYgk.........',
      '.kYYYgk.........',
      '.kYYygk.........',
      '.kYyygk.........',
      '.kyyyggk........',
      '.kyyyygkkk..kk..',
      '.kyyyyygggkkggk.',
      '..kyyyyyygggGk..',
      '..kyyyyyGGGGGk..',
      '...kkyyGGGGkk...',
      '.....kkkkkk.....',
      '................',
    ],
  },
  bolt: {
    palette: { k: INK, y: GOLD_HI, g: GOLD, w: WHITE, G: GOLD_DARK },
    rows: [
      '........kkkk....',
      '.......kyyygk...',
      '......kyyygk....',
      '.....kyyygk.....',
      '....kyyygk......',
      '...kyyygkkk.....',
      '..kyyyyywwgk....',
      '...kkkkyyGGk....',
      '.....kyygGk.....',
      '....kyygGk......',
      '...kyyGkk.......',
      '..kyGkk.........',
      '.kykk...........',
      '..k.............',
      '................',
      '................',
    ],
  },
  skull: {
    palette: { k: INK, b: BONE, w: WHITE, B: BONE_DIM, r: BLOOD_HI },
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkbbbbbbkk...',
      '..kbbwwbbbbbBk..',
      '.kbbwbbbbbbbbBk.',
      '.kbbbbbbbbbbbBk.',
      '.kbbkkkbbkkkbBk.',
      '.kbbkrkbbkrkbBk.',
      '.kbBkkkbbkkkBBk.',
      '..kbbbbkkbbbBk..',
      '...kbbbbbbbBk...',
      '...kbkbkbkbBk...',
      '...kBBBBBBBBk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ],
  },
  'potion-hp-s': {
    palette: {
      k: INK,
      h: WOOD_HI,
      H: WOOD,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      w: WHITE,
      l: HP_HI,
      m: HP,
      d: BLOOD_DARK,
    },
    rows: POTION_SMALL_ROWS,
  },
  'potion-hp-m': {
    palette: {
      k: INK,
      h: WOOD_HI,
      H: WOOD,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      l: HP_HI,
      m: HP,
      w: WHITE,
      d: BLOOD_DARK,
    },
    rows: POTION_MEDIUM_ROWS,
  },
  'potion-hp-l': {
    palette: {
      k: INK,
      h: WOOD_HI,
      H: WOOD,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      l: HP_HI,
      m: HP,
      w: WHITE,
      d: BLOOD_DARK,
      b: BONE,
      B: BONE_DIM,
      f: BONE_FAINT,
    },
    rows: POTION_LARGE_ROWS,
  },
  'potion-mp-s': {
    palette: {
      k: INK,
      h: WOOD_HI,
      H: WOOD,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      w: WHITE,
      l: MP_HI,
      m: MP,
      d: MP_DARK,
    },
    rows: POTION_SMALL_ROWS,
  },
  'potion-mp-m': {
    palette: {
      k: INK,
      h: WOOD_HI,
      H: WOOD,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      l: MP_HI,
      m: MP,
      w: WHITE,
      d: MP_DARK,
    },
    rows: POTION_MEDIUM_ROWS,
  },
  elixir: {
    palette: {
      k: INK,
      h: WOOD_HI,
      H: WOOD,
      c: STEEL_LIGHT,
      s: STEEL_HI,
      l: PURPLE_HI,
      m: PURPLE,
      w: WHITE,
      d: PURPLE_DARK,
      b: BONE,
      B: BONE_DIM,
      f: BONE_FAINT,
    },
    rows: POTION_LARGE_ROWS,
  },
  heart: {
    palette: { k: INK, r: BLOOD_HI, R: BLOOD, w: WHITE, q: BLOOD_DARK },
    rows: [
      '................',
      '................',
      '...kkk....kkk...',
      '..krrrk..kRRRk..',
      '.krwwrRkkRRRRqk.',
      '.krwrRRRRRRRRqk.',
      '.krrRRRRRRRRRqk.',
      '.krRRRRRRRRRqqk.',
      '..kRRRRRRRRqqk..',
      '...kRRRRRRqqk...',
      '....kRRRRqqk....',
      '.....kRRqqk.....',
      '......kqqk......',
      '.......kk.......',
      '................',
      '................',
    ],
  },
  mana: {
    palette: { k: INK, p: MP_HI, P: MP, w: WHITE, n: MP_DARK },
    rows: [
      '.......kk.......',
      '......kpPk......',
      '......kpPk......',
      '.....kppPPk.....',
      '.....kpwPPk.....',
      '....kppPPPPk....',
      '...kppwPPPPPk...',
      '...kpwPPPPPPk...',
      '..kppwPPPPPPnk..',
      '..kppPPPPPPPnk..',
      '..kpPPPPPPPnnk..',
      '..kpPPPPPPnnnk..',
      '...kPPPPPnnnk...',
      '....knnnnnnk....',
      '.....kkkkkk.....',
      '................',
    ],
  },
  coin: {
    palette: { k: INK, y: GOLD_HI, g: GOLD, G: GOLD_DARK },
    rows: [
      '................',
      '......kkkk......',
      '....kkyyyykk....',
      '...kyyyyyyggk...',
      '..kyyggggggGGk..',
      '..kygggGGgggGk..',
      '.kyggggGygggGGk.',
      '.kyggggGygggGGk.',
      '.kyggggGygggGGk.',
      '.kyggggGygggGGk.',
      '..kggggggggGGk..',
      '..kggggggGGGGk..',
      '...kGGGGGGGGk...',
      '....kkGGGGkk....',
      '......kkkk......',
      '................',
    ],
  },
  shop: {
    palette: {
      k: INK,
      R: BLOOD,
      b: BONE,
      q: BLOOD_DARK,
      B: BONE_DIM,
      h: WOOD_HI,
      c: STEEL_LIGHT,
      p: MP_HI,
      H: WOOD,
      D: WOOD_DARK,
      P: MP,
      g: GOLD,
      f: BONE_FAINT,
    },
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kRRbbRRbbRRbbk.',
      '.kRRbbRRbbRRbbk.',
      '.kqqBBqqBBqqBBk.',
      '..khhhhhhhhhhk..',
      '..khcpphhhhhHk..',
      '..khcpphDDDhHk..',
      '..khpPPhDDDhHk..',
      '..khhhhhDgDhHk..',
      '..khhhhhDDDhHk..',
      '..khhhhhDDDhHk..',
      '..kHHHHHDDDHHk..',
      '.kffffffffffffk.',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
  bag: {
    palette: { k: INK, o: RUST_HI, O: RUST, g: GOLD, G: GOLD_DARK, x: RUST_DARK },
    rows: [
      '................',
      '......kkk.......',
      '.....koOOk......',
      '....koooOOk.....',
      '.....kggGk......',
      '....kooooOk.....',
      '...koooooOOk....',
      '..kooooooOOOk...',
      '.kooooooooOOOk..',
      '.kooooooooOOOk..',
      '.kooooooooOOxk..',
      '.koooooooOOxxk..',
      '..kooooOOOxxk...',
      '...kxxxxxxxk....',
      '....kkkkkkk.....',
      '................',
    ],
  },
  gear: {
    palette: { k: INK, c: STEEL_LIGHT, s: STEEL_HI, S: STEEL },
    rows: [
      '.......kk.......',
      '......kcck......',
      '...kk.kcck.kk...',
      '..kcckcccckssk..',
      '..kccccccssssk..',
      '...kccccssssk...',
      '.kkcccckksssSkk.',
      'kccccck..ksSSSSk',
      'kccccsk..kSSSSSk',
      '.kkcssskkSSSSkk.',
      '...kssssSSSSk...',
      '..kssssSSSSSSk..',
      '..ksskSSSSkSSk..',
      '...kk.kSSk.kk...',
      '......kSSk......',
      '.......kk.......',
    ],
  },
  book: {
    palette: { k: INK, b: BONE, B: BONE_DIM, f: BONE_FAINT, R: BLOOD, q: BLOOD_DARK },
    rows: [
      '................',
      '................',
      '..kkk......kkk..',
      '.kbbbkk..kkbbbk.',
      'kbbbbbbkkbbbbbBk',
      'kbbbbbbbbbbbbbBk',
      'kbfffbbBBbfffbBk',
      'kbbbbbbBBbbbbbBk',
      'kbfffbbBBbfffbBk',
      'kbbbbbbBBbbbbbBk',
      'kbfffbbBBbfffbBk',
      'kbbbbbbBBbbbbbBk',
      'kRRRRRRqqRRRRRqk',
      '.kkRRRqkkqRRRkk.',
      '...kkkk..kkkk...',
      '................',
    ],
  },
  chart: {
    palette: {
      k: INK,
      t: TOXIC_HI,
      T: TOXIC,
      v: TOXIC_DARK,
      y: GOLD_HI,
      g: GOLD,
      G: GOLD_DARK,
      r: BLOOD_HI,
      R: BLOOD,
      q: BLOOD_DARK,
      b: BONE,
      B: BONE_DIM,
    },
    rows: [
      '................',
      '................',
      '..........kkk...',
      '.........ktTvk..',
      '.........ktTvk..',
      '......kkkktTvk..',
      '.....kygGktTvk..',
      '.....kygGktTvk..',
      '..kkkkygGktTvk..',
      '.krRqkygGktTvk..',
      '.krRqkygGktTvk..',
      '.krRqkygGktTvk..',
      '.krRqkygGktTvkk.',
      'kbbbbbbbbbbbbbBk',
      '.kkkkkkkkkkkkkk.',
      '................',
    ],
  },
  lock: {
    palette: { k: INK, c: STEEL_LIGHT, s: STEEL_HI, S: STEEL, y: GOLD_HI, g: GOLD, G: GOLD_DARK },
    rows: [
      '.....kkkkkk.....',
      '....kccccssk....',
      '...kcckkkkssk...',
      '...kcsk..ksSk...',
      '...kcsk..ksSk...',
      '...kcskkkksSk...',
      '..kyyyyyyyyggk..',
      '..kyggggggggGk..',
      '..kygggkkgggGk..',
      '..kygggkkgggGk..',
      '..kygggkkgggGk..',
      '..kyggggggggGk..',
      '..kGGGGGGGGGGk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
  },
  close: {
    palette: { k: INK, w: WHITE, b: BONE, B: BONE_DIM },
    rows: [
      '................',
      '..kk........kk..',
      '.kwbk......kwbk.',
      '.kbbbk....kwbBk.',
      '..kbbbk..kwbBk..',
      '...kbbbkkwbBk...',
      '....kbbwwbBk....',
      '.....kwbbBk.....',
      '.....kwbbBk.....',
      '....kwbBBbbk....',
      '...kwbBkkbbbk...',
      '..kwbBk..kbbbk..',
      '.kwbBk....kbbbk.',
      '.kbBk......kbBk.',
      '..kk........kk..',
      '................',
    ],
  },
  spark: {
    palette: { k: INK, w: WHITE, y: GOLD_HI, g: GOLD, G: GOLD_DARK },
    rows: [
      '.......kk.......',
      '......kwyk......',
      '......kygk......',
      '......kygk......',
      '.....kyyggk.....',
      '.....kyyggk.....',
      '.kkkkyywwggkkkk.',
      'kyyyyywwwwgggggk',
      'kgggggwwwwGGGGGk',
      '.kkkkggwwGGkkkk.',
      '.....kggGGk.....',
      '.....kggGGk.....',
      '......kgGk......',
      '......kgGk......',
      '......kGGk......',
      '.......kk.......',
    ],
  },
  zombie: {
    palette: {
      k: INK,
      z: STEEL_DARK,
      t: TOXIC_HI,
      T: TOXIC,
      v: TOXIC_DARK,
      y: GOLD_HI,
      b: BONE,
      R: BLOOD,
    },
    rows: [
      '......kk.k......',
      '.....kzzkzk.....',
      '....kzzzzzzk....',
      '...ktttttTTTk...',
      '..kttttTTTTTvk..',
      '..kttTTTTTTTvk..',
      '..ktTkkTTkkTvk..',
      '..ktTykTTkyTvk..',
      '..ktTTTTvTTTvk..',
      '..kTTTTTTTTTvk..',
      '..kTkbkbkbkTvk..',
      '..kvTTRTTTTvvk..',
      '...kvvvvvvvvk...',
      '....kkkkkkkk....',
      '................',
      '................',
    ],
  },
  boot: {
    palette: { k: INK, o: RUST_HI, O: RUST, h: WOOD_HI, H: WOOD, b: BONE, z: STEEL_DARK },
    rows: [
      '................',
      '...kkkkkkk......',
      '..kooooooOk.....',
      '..khhhhhhHk.....',
      '..khhhhhbHk.....',
      '..khhhhhbHk.....',
      '..khhhhhbHkk....',
      '..khhhhhhbHHk...',
      '..khhhhhhhhHHk..',
      '..khhhhhhhhhhHk.',
      '..khhhhhhhhhhhHk',
      '..kHHHHHHHHHHHHk',
      '..kzzzzzzzzzzzzk',
      '...kkkkkkkkkkkk.',
      '................',
      '................',
    ],
  },
  brain: {
    palette: { k: INK, i: PINK_HI, I: PINK, w: WHITE, J: PINK_DARK },
    rows: [
      '................',
      '................',
      '....kkkkkkkk....',
      '..kkiiiiiIIIkk..',
      '.kiwwiiJiIIJIIk.',
      'kiwiJJiiJIIJIIIk',
      'kiiJiiJJiIJJIJIk',
      'kiJiiiiJIJIIIJIk',
      'kiiJJiiJIIJJIIJk',
      '.kiiiJJIIJIIIJk.',
      '..kIIIIJIIJJJk..',
      '...kkkkkkIJkk...',
      '........kJJk....',
      '.........kk.....',
      '................',
      '................',
    ],
  },
  clover: {
    palette: { k: INK, t: TOXIC_HI, T: TOXIC, v: TOXIC_DARK },
    rows: [
      '................',
      '....kkk..kkk....',
      '...kttTkktttk...',
      '..kttTTkkttTTk..',
      '.kttTTvkktTTTvk.',
      '.ktTTvvkkTTTvvk.',
      '.kTTvvvkkTTvvvk.',
      '..kkkkkvvkkkkk..',
      '..kkkkkvvkkkkk..',
      '.ktttTTkvtttTTk.',
      '.kttTTTkvttTTvk.',
      '.ktTTTvkkvTTvvk.',
      '..kTTvvkkvTvvk..',
      '...kvvvkkTvvk...',
      '....kkk..kkvk...',
      '...........k....',
    ],
  },
  'arrow-up': {
    palette: { k: INK, w: WHITE, b: BONE, B: BONE_DIM },
    rows: [
      '................',
      '.......kk.......',
      '......kwbk......',
      '.....kwbbbk.....',
      '....kwbbbbbk....',
      '...kwbbbbbbbk...',
      '..kwbbbbbbbbbk..',
      '.kbBBbbbbbbBBbk.',
      '..kkkwbbbbBkkk..',
      '....kwbbbbBk....',
      '....kwbbbbBk....',
      '....kwbbbbBk....',
      '....kwbbbbBk....',
      '....kbBBBBBk....',
      '.....kkkkkk.....',
      '................',
    ],
  },
  'arrow-down': {
    palette: { k: INK, w: WHITE, b: BONE, B: BONE_DIM },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwbk....',
      '....kwbbbbBk....',
      '....kwbbbbBk....',
      '....kwbbbbBk....',
      '....kwbbbbBk....',
      '..kkkwbbbbBkkk..',
      '.kbwwbbbbbbwwbk.',
      '..kbbbbbbbbbBk..',
      '...kbbbbbbbBk...',
      '....kbbbbbBk....',
      '.....kbbbBk.....',
      '......kbBk......',
      '.......kk.......',
      '................',
    ],
  },
  'arrow-left': {
    palette: { k: INK, b: BONE, w: WHITE, B: BONE_DIM },
    rows: [
      '................',
      '.......k........',
      '......kbk.......',
      '.....kwBk.......',
      '....kwbBkkkkkk..',
      '...kwbbbwwwwwbk.',
      '..kwbbbbbbbbbBk.',
      '.kwbbbbbbbbbbBk.',
      '.kbbbbbbbbbbbBk.',
      '..kbbbbbbbbbbBk.',
      '...kbbbbBBBBBBk.',
      '....kbbBkkkkkk..',
      '.....kbBk.......',
      '......kbk.......',
      '.......k........',
      '................',
    ],
  },
  'arrow-right': {
    palette: { k: INK, b: BONE, w: WHITE, B: BONE_DIM },
    rows: [
      '................',
      '........k.......',
      '.......kbk......',
      '.......kwbk.....',
      '..kkkkkkwbbk....',
      '.kwwwwwwbbbbk...',
      '.kwbbbbbbbbbbk..',
      '.kwbbbbbbbbbbbk.',
      '.kwbbbbbbbbbbBk.',
      '.kwbbbbbbbbbBk..',
      '.kbBBBBBbbbBk...',
      '..kkkkkkwbBk....',
      '.......kwBk.....',
      '.......kbk......',
      '........k.......',
      '................',
    ],
  },
  slot: {
    palette: { k: INK, s: STEEL_HI, S: STEEL, z: STEEL_DARK, c: STEEL_LIGHT, d: INK_2 },
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.ksssssssssssSk.',
      '.kszzzzzzzzzcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszddddddddcSk.',
      '.kszcccccccccSk.',
      '.kSSSSSSSSSSSSk.',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
  revive: {
    palette: { k: INK, r: BLOOD_HI, R: BLOOD, w: WHITE, q: BLOOD_DARK, b: BONE },
    rows: [
      '................',
      '................',
      '...kkk....kkk...',
      '..krrrk..kRRRk..',
      '.krwwrRkkRRRRqk.',
      '.krwrRRbbRRRRqk.',
      '.krrRbbbbbbRRqk.',
      '.krRRbbbbbbRqqk.',
      '..kRRRRbbRRqqk..',
      '...kRRRbbRqqk...',
      '....kRRRRqqk....',
      '.....kRRqqk.....',
      '......kqqk......',
      '.......kk.......',
      '................',
      '................',
    ],
  },
};
