import {
  CharacterClass,
  CharacterClassDefinition,
  CharacterStats,
} from './character';
import {
  ZombieType,
  ZombieDefinition,
  DropType,
  ShopItemDefinition,
} from './game-entities';
import { KeyBindings } from './messages';
import { SkillDefinition, SkillType } from './skill';

// ═══════════════════════════════════════════════════════════════
//  GAME CONSTANTS
//  Single source of truth for ALL tunable game variables.
//  Edit this file to adjust game balance, physics, combat, etc.
// ═══════════════════════════════════════════════════════════════

export const GAME_CONSTANTS = {

  // ─── Canvas & World ─────────────────────────────
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  GROUND_Y: 620,
  BACKGROUND_STAR_COUNT: 80,

  // ─── Physics ────────────────────────────────────
  GRAVITY: 0.5,
  TERMINAL_VELOCITY: 25,
  PLATFORM_SNAP_TOLERANCE: 6,
  PLATFORM_DROP_TICKS: 8,

  // ─── Player Movement ────────────────────────────
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  PLAYER_JUMP_FORCE: -10,
  PLAYER_MOVE_SPEED: 5,
  PLAYER_FRICTION: .9,
  PLAYER_AIR_DRAG: 0.98,
  PLAYER_MIN_VELOCITY: 1,

  // ─── Player Combat ─────────────────────────────
  PLAYER_BASE_ATTACK_RANGE: 50,
  PLAYER_ATTACK_COOLDOWN_TICKS: 24,
  PLAYER_ATTACK_ANIM_MS: 480,
  PLAYER_ATTACK_HIT_DELAY_MS: 240,
  PLAYER_SKILL_ANIM_MS: 480,
  INVINCIBILITY_FRAMES: 90,
  INVINCIBILITY_BLINK_RATE: 3,

  // ─── Knockback ──────────────────────────────────
  KNOCKBACK_FORCE_PLAYER: 6,
  KNOCKBACK_UP_FORCE: -5,
  KNOCKBACK_ZOMBIE_FRAMES: 10,

  // ─── Player Derived Stat Formulas ───────────────
  PLAYER_BASE_HP: 50,
  PLAYER_BASE_MP: 30,
  PLAYER_HP_PER_LEVEL: 25,
  PLAYER_MP_PER_LEVEL: 3,
  PLAYER_SPEED_PER_DEX: 0.05,
  PLAYER_CRIT_RATE_CAP: 60,
  PLAYER_CRIT_DAMAGE_BASE: 150,

  // ─── XP & Leveling ─────────────────────────────
  XP_BASE: 120,
  XP_GROWTH: 1.6,
  STAT_POINTS_PER_LEVEL: 5,
  SKILL_POINTS_PER_LEVEL: 3,
  MAX_SKILL_LEVEL: 20,

  // ─── Waves ──────────────────────────────────────
  WAVE_ZOMBIE_COUNT_BASE: 5,
  WAVE_ZOMBIE_COUNT_GROWTH: 3,
  WAVE_TRANSITION_TICKS: 120,
  WAVE_INITIAL_SPAWN_DELAY_TICKS: 60,

  // ─── Zombie Spawning ───────────────────────────
  ZOMBIE_SPAWN_INTERVAL_MS: 2000,
  ZOMBIE_SPAWN_MIN_INTERVAL_MS: 500,
  ZOMBIE_SPAWN_DECREASE_PER_WAVE: 100,
  ZOMBIE_HP_SCALE_PER_WAVE: 0.15,
  ZOMBIE_RUNNER_MIN_WAVE: 2,
  ZOMBIE_RUNNER_ROLL_THRESHOLD: 0.7,
  ZOMBIE_TANK_MIN_WAVE: 3,
  ZOMBIE_TANK_ROLL_THRESHOLD: 0.85,
  ZOMBIE_SPITTER_MIN_WAVE: 4,
  ZOMBIE_SPITTER_ROLL_THRESHOLD: 0.6,
  ZOMBIE_BOSS_MIN_WAVE: 5,
  ZOMBIE_BOSS_WAVE_INTERVAL: 5,
  ZOMBIE_DRAGON_BOSS_MIN_WAVE: 10,
  ZOMBIE_DRAGON_BOSS_WAVE_INTERVAL: 10,

  // ─── Dragon Boss ─────────────────────────────
  DRAGON_HOVER_Y_OFFSET: 140,
  DRAGON_ATTACK_RANGE: 350,
  DRAGON_KEEP_DISTANCE: 280,
  DRAGON_APPROACH_SPEED_MULT: 0.6,
  DRAGON_PROJECTILE_SPEED: 7,
  DRAGON_PROJECTILE_LIFETIME: 100,

  // ─── Zombie AI ────────────────────────────────
  ZOMBIE_ORBIT_MIN: 25,
  ZOMBIE_ORBIT_MAX: 55,
  ZOMBIE_ORBIT_ARRIVE_THRESHOLD: 15,
  ZOMBIE_JUMP_FORCE: -9.5,
  ZOMBIE_JUMP_COOLDOWN_MIN: 80,
  ZOMBIE_JUMP_COOLDOWN_MAX: 200,
  ZOMBIE_JUMP_CHANCE_PER_TICK: 0.015,
  ZOMBIE_JUMP_PLATFORM_CHASE_CHANCE: 0.04,
  ZOMBIE_ATTACK_RANGE: 35,
  ZOMBIE_ATTACK_COOLDOWN_MIN: 40,
  ZOMBIE_ATTACK_COOLDOWN_MAX: 70,
  ZOMBIE_ATTACK_ANIM_TICKS: 12,
  ZOMBIE_ATTACK_HIT_TICK: 6,
  ZOMBIE_HESITATION_RANGE_MIN: 0,
  ZOMBIE_HESITATION_RANGE_MAX: 40,
  ZOMBIE_CONTACT_DAMAGE_MULT: 0.3,
  ZOMBIE_PLATFORM_DROP_TICKS: 10,
  ZOMBIE_PLATFORM_DROP_CHANCE: 0.03,

  // ─── Zombie Spawn Animation ────────────────────
  ZOMBIE_SPAWN_ANIM_TICKS: 50,

  // ─── Zombie Corpse Fade ─────────────────────────
  ZOMBIE_CORPSE_LINGER_TICKS: 120,

  // ─── Ropes ──────────────────────────────────────
  ROPE_CLIMB_SPEED: 5,
  ROPE_WIDTH: 20,
  ROPE_GRAB_RANGE: 24,
  ROPE_JUMP_COOLDOWN_TICKS: 12,

  // ─── Particles ──────────────────────────────────
  MAX_PARTICLES: 400,
  PARTICLE_LIFETIME_MS: 600,
  HIT_PARTICLE_COUNT: 6,
  HIT_PARTICLE_VELOCITY: 6,
  HIT_PARTICLE_UP_BIAS: 2,
  HIT_PARTICLE_LIFE: 30,
  DEATH_PARTICLE_COUNT: 15,
  DEATH_PARTICLE_VELOCITY: 10,
  DEATH_PARTICLE_UP_BIAS: 3,
  DEATH_PARTICLE_LIFE: 45,
  PARTICLE_GRAVITY: 0.15,

  // ─── Damage Numbers ────────────────────────────
  DAMAGE_NUMBER_LIFE_TICKS: 60,

  // ─── Drop Rates ───────────────────────────────
  DROP_HP_POTION_CHANCE: 0.02,
  DROP_MP_POTION_CHANCE: 0.02,
  DROP_GOLD_CHANCE: 0.55,
  DROP_GOLD_MIN: 5,
  DROP_GOLD_MAX: 25,
  DROP_GOLD_WAVE_BONUS: 3,
  DROP_LIFETIME: 600,
  DROP_SIZE: 14,
  DROP_POP_FORCE: -2,

  // ─── Potions ──────────────────────────────────
  HP_POTION_RESTORE: 50,
  MP_POTION_RESTORE: 30,
  POTION_USE_COOLDOWN_TICKS: 30,

  // ─── Shop ────────────────────────────────────
  SHOP_HP_POTION_PRICE: 30,
  SHOP_MP_POTION_PRICE: 20,

  // ─── Tick Rate ──────────────────────────────────
  TICK_RATE: 50,

} as const;

// ─── Class Stat Weights (MapleStory-style) ──────

export interface ClassStatWeights {
  primaryStat: keyof CharacterStats;
  secondaryStat: keyof CharacterStats;
  attackFromPrimary: number;
  attackFromSecondary: number;
  defenseFromStr: number;
  defenseFromDex: number;
  hpPerStr: number;
  mpPerInt: number;
  critFromLuk: number;
  critDmgFromLuk: number;
}

export const CLASS_STAT_WEIGHTS: Record<CharacterClass, ClassStatWeights> = {
  [CharacterClass.Warrior]: {
    primaryStat: 'str',
    secondaryStat: 'dex',
    attackFromPrimary: 3.5,
    attackFromSecondary: 1.0,
    defenseFromStr: 1.5,
    defenseFromDex: 0.5,
    hpPerStr: 12,
    mpPerInt: 4,
    critFromLuk: 0.5,
    critDmgFromLuk: 1.0,
  },
  [CharacterClass.Ranger]: {
    primaryStat: 'dex',
    secondaryStat: 'str',
    attackFromPrimary: 3.5,
    attackFromSecondary: 1.0,
    defenseFromStr: 0.5,
    defenseFromDex: 1.0,
    hpPerStr: 8,
    mpPerInt: 6,
    critFromLuk: 1.0,
    critDmgFromLuk: 1.5,
  },
  [CharacterClass.Mage]: {
    primaryStat: 'int',
    secondaryStat: 'luk',
    attackFromPrimary: 4.0,
    attackFromSecondary: 0.5,
    defenseFromStr: 0.3,
    defenseFromDex: 0.3,
    hpPerStr: 6,
    mpPerInt: 14,
    critFromLuk: 1.0,
    critDmgFromLuk: 2.0,
  },
  [CharacterClass.Assassin]: {
    primaryStat: 'luk',
    secondaryStat: 'dex',
    attackFromPrimary: 3.0,
    attackFromSecondary: 1.5,
    defenseFromStr: 0.5,
    defenseFromDex: 1.0,
    hpPerStr: 7,
    mpPerInt: 5,
    critFromLuk: 2.0,
    critDmgFromLuk: 3.0,
  },
  [CharacterClass.Priest]: {
    primaryStat: 'int',
    secondaryStat: 'luk',
    attackFromPrimary: 3.5,
    attackFromSecondary: 0.8,
    defenseFromStr: 0.5,
    defenseFromDex: 0.5,
    hpPerStr: 8,
    mpPerInt: 12,
    critFromLuk: 0.8,
    critDmgFromLuk: 1.5,
  },
};

// ─── Character Classes ───────────────────────────

export const CHARACTER_CLASSES: Record<CharacterClass, CharacterClassDefinition> = {
  [CharacterClass.Warrior]: {
    id: CharacterClass.Warrior,
    name: 'Warrior',
    description: 'Heavy melee fighter with high HP and defense. Cleaves through zombie hordes.',
    baseStats: { str: 15, dex: 8, int: 4, luk: 6 },
    color: '#ff4444',
    icon: '⚔️',
  },
  [CharacterClass.Ranger]: {
    id: CharacterClass.Ranger,
    name: 'Ranger',
    description: 'Ranged attacker with high DEX. Picks off zombies from a safe distance.',
    baseStats: { str: 8, dex: 15, int: 6, luk: 8 },
    color: '#44cc44',
    icon: '🏹',
  },
  [CharacterClass.Mage]: {
    id: CharacterClass.Mage,
    name: 'Mage',
    description: 'Wields devastating AoE magic. Fragile but deals massive damage.',
    baseStats: { str: 4, dex: 6, int: 18, luk: 5 },
    color: '#6644ff',
    icon: '🔮',
  },
  [CharacterClass.Assassin]: {
    id: CharacterClass.Assassin,
    name: 'Assassin',
    description: 'Lightning-fast strikes and high crit chance. Thrives on lucky hits.',
    baseStats: { str: 10, dex: 12, int: 4, luk: 14 },
    color: '#cc44cc',
    icon: '🗡️',
  },
  [CharacterClass.Priest]: {
    id: CharacterClass.Priest,
    name: 'Priest',
    description: 'Support class that heals allies and smites undead with holy damage.',
    baseStats: { str: 6, dex: 6, int: 14, luk: 8 },
    color: '#ffcc44',
    icon: '✨',
  },
};

// ─── Zombie Types ────────────────────────────────

export const ZOMBIE_TYPES: Record<ZombieType, ZombieDefinition> = {
  [ZombieType.Walker]: {
    type: ZombieType.Walker,
    name: 'Walker',
    hpMin: 22, hpMax: 40,
    damageMinLow: 22, damageMinHigh: 38,
    damageMaxLow: 40, damageMaxHigh: 60,
    speedMin: 0.4, speedMax: 0.8,
    knockbackMin: 6, knockbackMax: 10,
    hesitationMin: 70, hesitationMax: 110,
    xpRewardMin: 4, xpRewardMax: 7,
    width: 28,
    height: 40,
    attackAnimTicks: 20,
    attackHitTick: 10,
  },
  [ZombieType.Runner]: {
    type: ZombieType.Runner,
    name: 'Runner',
    hpMin: 14, hpMax: 28,
    damageMinLow: 22, damageMinHigh: 38,
    damageMaxLow: 40, damageMaxHigh: 60,
    speedMin: 1.4, speedMax: 2.3,
    knockbackMin: 4, knockbackMax: 8,
    hesitationMin: 35, hesitationMax: 65,
    xpRewardMin: 6, xpRewardMax: 11,
    width: 24,
    height: 36,
    attackAnimTicks: 20,
    attackHitTick: 10,
  },
  [ZombieType.Tank]: {
    type: ZombieType.Tank,
    name: 'Tank',
    hpMin: 75, hpMax: 135,
    damageMinLow: 7, damageMinHigh: 14,
    damageMaxLow: 16, damageMaxHigh: 28,
    speedMin: 0.2, speedMax: 0.45,
    knockbackMin: 3, knockbackMax: 6,
    hesitationMin: 85, hesitationMax: 130,
    xpRewardMin: 12, xpRewardMax: 20,
    width: 40,
    height: 48,
    attackAnimTicks: 30,
    attackHitTick: 15,
  },
  [ZombieType.Spitter]: {
    type: ZombieType.Spitter,
    name: 'Spitter',
    hpMin: 18, hpMax: 35,
    damageMinLow: 5, damageMinHigh: 12,
    damageMaxLow: 12, damageMaxHigh: 20,
    speedMin: 0.65, speedMax: 1.2,
    knockbackMin: 5, knockbackMax: 9,
    hesitationMin: 75, hesitationMax: 115,
    xpRewardMin: 7, xpRewardMax: 14,
    width: 26,
    height: 38,
    attackAnimTicks: 20,
    attackHitTick: 10,
  },
  [ZombieType.Boss]: {
    type: ZombieType.Boss,
    name: 'Undead King',
    hpMin: 400, hpMax: 650,
    damageMinLow: 18, damageMinHigh: 32,
    damageMaxLow: 35, damageMaxHigh: 50,
    speedMin: 0.35, speedMax: 0.65,
    knockbackMin: 3, knockbackMax: 5,
    hesitationMin: 45, hesitationMax: 80,
    xpRewardMin: 80, xpRewardMax: 130,
    width: 56,
    height: 64,
    attackAnimTicks: 20,
    attackHitTick: 10,
  },
  [ZombieType.DragonBoss]: {
    type: ZombieType.DragonBoss,
    name: 'Ancient Dragon',
    hpMin: 1600, hpMax: 2500,
    damageMinLow: 40, damageMinHigh: 65,
    damageMaxLow: 70, damageMaxHigh: 100,
    speedMin: 0.5, speedMax: 0.9,
    knockbackMin: 3, knockbackMax: 5,
    hesitationMin: 25, hesitationMax: 55,
    xpRewardMin: 800, xpRewardMax: 1250,
    width: 80,
    height: 80,
    attackAnimTicks: 36,
    attackHitTick: 18,
  },
};

// ─── Skills ─────────────────────────────────────

export const SKILLS: SkillDefinition[] = [

  // ═══ WARRIOR ═══
  {
    id: 'warrior-power-strike',
    name: 'Power Strike',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Use MP to deliver a killer blow to a single monster with a melee weapon.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '⚔️',
    color: '#ff4444',
    scaling: {
      baseDamage: 1.65, damagePerLevel: 0.05,
      baseMpCost: 4, mpCostPerLevel: 0.42,
      baseCooldown: 800, cooldownReductionPerLevel: 15,
      baseRange: 55, rangePerLevel: 1,
    },
    levelData: [
      { mpCost: 4,  hpCost: 0, damage: 1.65 },
      { mpCost: 4,  hpCost: 0, damage: 1.70 },
      { mpCost: 4,  hpCost: 0, damage: 1.75 },
      { mpCost: 4,  hpCost: 0, damage: 1.80 },
      { mpCost: 5,  hpCost: 0, damage: 1.85 },
      { mpCost: 5,  hpCost: 0, damage: 1.90 },
      { mpCost: 5,  hpCost: 0, damage: 1.95 },
      { mpCost: 6,  hpCost: 0, damage: 2.00 },
      { mpCost: 6,  hpCost: 0, damage: 2.05 },
      { mpCost: 7,  hpCost: 0, damage: 2.10 },
      { mpCost: 7,  hpCost: 0, damage: 2.15 },
      { mpCost: 8,  hpCost: 0, damage: 2.20 },
      { mpCost: 8,  hpCost: 0, damage: 2.25 },
      { mpCost: 9,  hpCost: 0, damage: 2.30 },
      { mpCost: 9,  hpCost: 0, damage: 2.35 },
      { mpCost: 10, hpCost: 0, damage: 2.40 },
      { mpCost: 10, hpCost: 0, damage: 2.45 },
      { mpCost: 11, hpCost: 0, damage: 2.50 },
      { mpCost: 11, hpCost: 0, damage: 2.55 },
      { mpCost: 12, hpCost: 0, damage: 2.60 },
    ],
    prerequisite: null,
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'warrior-power-strike',
    passiveEffect: null,
    mechanic: 'damage',
    maxTargets: 1,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },
  {
    id: 'warrior-slash-blast',
    name: 'Slash Blast',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Use HP and MP to attack up to 6 enemies around you with a melee weapon.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🌀',
    color: '#ff6644',
    scaling: {
      baseDamage: 0.72, damagePerLevel: 0.03,
      baseMpCost: 6, mpCostPerLevel: 0.42,
      baseCooldown: 1200, cooldownReductionPerLevel: 20,
      baseRange: 80, rangePerLevel: 2,
    },
    levelData: [
      { mpCost: 6,  hpCost: 8,  damage: 0.72 },
      { mpCost: 6,  hpCost: 8,  damage: 0.75 },
      { mpCost: 6,  hpCost: 8,  damage: 0.78 },
      { mpCost: 6,  hpCost: 8,  damage: 0.81 },
      { mpCost: 7,  hpCost: 9,  damage: 0.84 },
      { mpCost: 7,  hpCost: 9,  damage: 0.87 },
      { mpCost: 7,  hpCost: 9,  damage: 0.90 },
      { mpCost: 8,  hpCost: 10, damage: 0.93 },
      { mpCost: 8,  hpCost: 10, damage: 0.96 },
      { mpCost: 9,  hpCost: 11, damage: 0.99 },
      { mpCost: 9,  hpCost: 11, damage: 1.02 },
      { mpCost: 10, hpCost: 12, damage: 1.05 },
      { mpCost: 10, hpCost: 12, damage: 1.08 },
      { mpCost: 11, hpCost: 13, damage: 1.11 },
      { mpCost: 11, hpCost: 13, damage: 1.14 },
      { mpCost: 12, hpCost: 14, damage: 1.17 },
      { mpCost: 12, hpCost: 14, damage: 1.20 },
      { mpCost: 13, hpCost: 15, damage: 1.23 },
      { mpCost: 13, hpCost: 15, damage: 1.26 },
      { mpCost: 14, hpCost: 16, damage: 1.30 },
    ],
    prerequisite: { skillId: 'warrior-power-strike', level: 1 },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 80,
    animationKey: 'warrior-slash-blast',
    passiveEffect: null,
    mechanic: 'damage',
    maxTargets: 6,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },

  // ═══ WARRIOR ACTIVE (Dash) ═══
  {
    id: 'warrior-power-dash',
    name: 'Power Dash',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Make a mad dash forward, pushing off up to 10 monsters.',
    maxLevel: 30,
    requiredCharacterLevel: 10,
    icon: '💨',
    color: '#ff8844',
    scaling: {
      baseDamage: 0.72, damagePerLevel: 0.02,
      baseMpCost: 22, mpCostPerLevel: 2,
      baseCooldown: 1500, cooldownReductionPerLevel: 20,
      baseRange: 200, rangePerLevel: 4,
    },
    levelData: [
      { mpCost: 22, hpCost: 0, damage: 0.72, range: 200 },
      { mpCost: 24, hpCost: 0, damage: 0.74, range: 200 },
      { mpCost: 26, hpCost: 0, damage: 0.76, range: 200 },
      { mpCost: 28, hpCost: 0, damage: 0.78, range: 213 },
      { mpCost: 30, hpCost: 0, damage: 0.80, range: 213 },
      { mpCost: 32, hpCost: 0, damage: 0.82, range: 213 },
      { mpCost: 34, hpCost: 0, damage: 0.84, range: 213 },
      { mpCost: 36, hpCost: 0, damage: 0.86, range: 225 },
      { mpCost: 38, hpCost: 0, damage: 0.88, range: 225 },
      { mpCost: 40, hpCost: 0, damage: 0.90, range: 225 },
      { mpCost: 42, hpCost: 0, damage: 0.92, range: 238 },
      { mpCost: 44, hpCost: 0, damage: 0.94, range: 238 },
      { mpCost: 46, hpCost: 0, damage: 0.96, range: 238 },
      { mpCost: 48, hpCost: 0, damage: 0.98, range: 250 },
      { mpCost: 50, hpCost: 0, damage: 1.00, range: 250 },
      { mpCost: 52, hpCost: 0, damage: 1.02, range: 250 },
      { mpCost: 54, hpCost: 0, damage: 1.04, range: 263 },
      { mpCost: 56, hpCost: 0, damage: 1.06, range: 263 },
      { mpCost: 58, hpCost: 0, damage: 1.08, range: 263 },
      { mpCost: 60, hpCost: 0, damage: 1.10, range: 275 },
      { mpCost: 59, hpCost: 0, damage: 1.12, range: 275 },
      { mpCost: 58, hpCost: 0, damage: 1.14, range: 288 },
      { mpCost: 57, hpCost: 0, damage: 1.16, range: 288 },
      { mpCost: 56, hpCost: 0, damage: 1.18, range: 288 },
      { mpCost: 55, hpCost: 0, damage: 1.20, range: 300 },
      { mpCost: 54, hpCost: 0, damage: 1.22, range: 300 },
      { mpCost: 53, hpCost: 0, damage: 1.24, range: 300 },
      { mpCost: 52, hpCost: 0, damage: 1.26, range: 313 },
      { mpCost: 51, hpCost: 0, damage: 1.28, range: 313 },
      { mpCost: 50, hpCost: 0, damage: 1.30, range: 313 },
    ],
    prerequisite: { skillId: 'warrior-slash-blast', level: 5 },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'warrior-power-dash',
    passiveEffect: null,
    mechanic: 'dash',
    maxTargets: 10,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },

  // ═══ WARRIOR PASSIVE ═══
  {
    id: 'warrior-improved-hp-recovery',
    name: 'Improved HP Recovery',
    classId: CharacterClass.Warrior,
    type: SkillType.Passive,
    description: 'Recover additional HP every 10 seconds while standing still.',
    maxLevel: 16,
    requiredCharacterLevel: 1,
    icon: '💚',
    color: '#44cc44',
    scaling: {
      baseDamage: 3, damagePerLevel: 3,
      baseMpCost: 0, mpCostPerLevel: 0,
      baseCooldown: 0, cooldownReductionPerLevel: 0,
      baseRange: 0, rangePerLevel: 0,
    },
    levelData: [
      { mpCost: 0, hpCost: 0, damage: 3 },
      { mpCost: 0, hpCost: 0, damage: 6 },
      { mpCost: 0, hpCost: 0, damage: 9 },
      { mpCost: 0, hpCost: 0, damage: 12 },
      { mpCost: 0, hpCost: 0, damage: 15 },
      { mpCost: 0, hpCost: 0, damage: 18 },
      { mpCost: 0, hpCost: 0, damage: 21 },
      { mpCost: 0, hpCost: 0, damage: 24 },
      { mpCost: 0, hpCost: 0, damage: 27 },
      { mpCost: 0, hpCost: 0, damage: 30 },
      { mpCost: 0, hpCost: 0, damage: 33 },
      { mpCost: 0, hpCost: 0, damage: 36 },
      { mpCost: 0, hpCost: 0, damage: 39 },
      { mpCost: 0, hpCost: 0, damage: 42 },
      { mpCost: 0, hpCost: 0, damage: 45 },
      { mpCost: 0, hpCost: 0, damage: 50 },
    ],
    prerequisite: null,
    buffEffect: null,
    buffDuration: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: '',
    passiveEffect: {
      type: 'hpRecovery',
      intervalMs: 10_000,
      condition: 'standingStill',
    },
    mechanic: 'damage',
    maxTargets: 0,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },

  // ═══ WARRIOR BUFF (Defensive) ═══
  {
    id: 'warrior-power-stance',
    name: 'Power Stance',
    classId: CharacterClass.Warrior,
    type: SkillType.Buff,
    description: 'Enables one to stay at the same spot after being struck, resisting knock-back effects.',
    maxLevel: 30,
    requiredCharacterLevel: 7,
    icon: '🛡️',
    color: '#ff9944',
    scaling: {
      baseDamage: 42, damagePerLevel: 1.65,
      baseMpCost: 30, mpCostPerLevel: 0.8,
      baseCooldown: 1000, cooldownReductionPerLevel: 0,
      baseRange: 0, rangePerLevel: 0,
    },
    levelData: [
      { mpCost: 30, hpCost: 0, damage: 42 },
      { mpCost: 30, hpCost: 0, damage: 44 },
      { mpCost: 30, hpCost: 0, damage: 46 },
      { mpCost: 30, hpCost: 0, damage: 48 },
      { mpCost: 30, hpCost: 0, damage: 50 },
      { mpCost: 36, hpCost: 0, damage: 52 },
      { mpCost: 36, hpCost: 0, damage: 54 },
      { mpCost: 36, hpCost: 0, damage: 56 },
      { mpCost: 36, hpCost: 0, damage: 58 },
      { mpCost: 36, hpCost: 0, damage: 60 },
      { mpCost: 42, hpCost: 0, damage: 62 },
      { mpCost: 42, hpCost: 0, damage: 64 },
      { mpCost: 42, hpCost: 0, damage: 66 },
      { mpCost: 42, hpCost: 0, damage: 68 },
      { mpCost: 42, hpCost: 0, damage: 70 },
      { mpCost: 48, hpCost: 0, damage: 72 },
      { mpCost: 48, hpCost: 0, damage: 74 },
      { mpCost: 48, hpCost: 0, damage: 76 },
      { mpCost: 48, hpCost: 0, damage: 78 },
      { mpCost: 48, hpCost: 0, damage: 80 },
      { mpCost: 54, hpCost: 0, damage: 81 },
      { mpCost: 54, hpCost: 0, damage: 82 },
      { mpCost: 54, hpCost: 0, damage: 83 },
      { mpCost: 54, hpCost: 0, damage: 84 },
      { mpCost: 54, hpCost: 0, damage: 85 },
      { mpCost: 53, hpCost: 0, damage: 86 },
      { mpCost: 52, hpCost: 0, damage: 87 },
      { mpCost: 51, hpCost: 0, damage: 88 },
      { mpCost: 50, hpCost: 0, damage: 89 },
      { mpCost: 50, hpCost: 0, damage: 90 },
    ],
    prerequisite: null,
    buffEffect: { stat: 'knockbackResist', baseValue: 42, valuePerLevel: 1.65 },
    buffDuration: { baseDurationMs: 10_000, durationPerLevelMs: 10_000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-power-stance',
    passiveEffect: null,
    mechanic: 'damage',
    maxTargets: 0,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },

  // ═══ WARRIOR BUFF (Party) ═══
  {
    id: 'warrior-hyper-body',
    name: 'Hyper Body',
    classId: CharacterClass.Warrior,
    type: SkillType.Buff,
    description: 'Temporarily increases the Max HP and Max MP of all party members in the area.',
    maxLevel: 30,
    requiredCharacterLevel: 10,
    icon: '💪',
    color: '#44ddaa',
    scaling: {
      baseDamage: 2, damagePerLevel: 2,
      baseMpCost: 20, mpCostPerLevel: 1.4,
      baseCooldown: 1000, cooldownReductionPerLevel: 0,
      baseRange: 0, rangePerLevel: 0,
    },
    levelData: [
      { mpCost: 20, hpCost: 0, damage: 2 },
      { mpCost: 20, hpCost: 0, damage: 4 },
      { mpCost: 20, hpCost: 0, damage: 6 },
      { mpCost: 20, hpCost: 0, damage: 8 },
      { mpCost: 20, hpCost: 0, damage: 10 },
      { mpCost: 20, hpCost: 0, damage: 12 },
      { mpCost: 20, hpCost: 0, damage: 14 },
      { mpCost: 20, hpCost: 0, damage: 16 },
      { mpCost: 20, hpCost: 0, damage: 18 },
      { mpCost: 20, hpCost: 0, damage: 20 },
      { mpCost: 40, hpCost: 0, damage: 22 },
      { mpCost: 40, hpCost: 0, damage: 24 },
      { mpCost: 40, hpCost: 0, damage: 26 },
      { mpCost: 40, hpCost: 0, damage: 28 },
      { mpCost: 40, hpCost: 0, damage: 30 },
      { mpCost: 40, hpCost: 0, damage: 32 },
      { mpCost: 40, hpCost: 0, damage: 34 },
      { mpCost: 40, hpCost: 0, damage: 36 },
      { mpCost: 40, hpCost: 0, damage: 38 },
      { mpCost: 40, hpCost: 0, damage: 40 },
      { mpCost: 60, hpCost: 0, damage: 42 },
      { mpCost: 60, hpCost: 0, damage: 44 },
      { mpCost: 60, hpCost: 0, damage: 46 },
      { mpCost: 60, hpCost: 0, damage: 48 },
      { mpCost: 50, hpCost: 0, damage: 50 },
      { mpCost: 60, hpCost: 0, damage: 52 },
      { mpCost: 60, hpCost: 0, damage: 54 },
      { mpCost: 60, hpCost: 0, damage: 56 },
      { mpCost: 60, hpCost: 0, damage: 58 },
      { mpCost: 60, hpCost: 0, damage: 60 },
    ],
    prerequisite: null,
    buffEffect: { stat: 'maxHpMaxMpPercent', baseValue: 2, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 10_000, durationPerLevelMs: 10_000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-hyper-body',
    passiveEffect: null,
    mechanic: 'damage',
    maxTargets: 0,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },

  // ═══ WARRIOR ACTIVE (Utility) ═══
  {
    id: 'warrior-monster-magnet',
    name: 'Monster Magnet',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Pulls all monsters from afar (within range) right to you.',
    maxLevel: 30,
    requiredCharacterLevel: 5,
    icon: '🧲',
    color: '#cc44ff',
    scaling: {
      baseDamage: 0, damagePerLevel: 0,
      baseMpCost: 10, mpCostPerLevel: 0,
      baseCooldown: 8000, cooldownReductionPerLevel: 80,
      baseRange: 50, rangePerLevel: 0,
    },
    levelData: [
      { mpCost: 10, hpCost: 0, damage: 0, range: 50 },
      { mpCost: 10, hpCost: 0, damage: 0, range: 50 },
      { mpCost: 10, hpCost: 0, damage: 0, range: 50 },
      { mpCost: 10, hpCost: 0, damage: 0, range: 50 },
      { mpCost: 10, hpCost: 0, damage: 0, range: 50 },
      { mpCost: 13, hpCost: 0, damage: 0, range: 100 },
      { mpCost: 13, hpCost: 0, damage: 0, range: 100 },
      { mpCost: 13, hpCost: 0, damage: 0, range: 100 },
      { mpCost: 13, hpCost: 0, damage: 0, range: 100 },
      { mpCost: 13, hpCost: 0, damage: 0, range: 100 },
      { mpCost: 18, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 18, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 18, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 18, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 18, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 21, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 21, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 21, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 21, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 21, hpCost: 0, damage: 0, range: 150 },
      { mpCost: 26, hpCost: 0, damage: 0, range: 200 },
      { mpCost: 26, hpCost: 0, damage: 0, range: 200 },
      { mpCost: 26, hpCost: 0, damage: 0, range: 200 },
      { mpCost: 26, hpCost: 0, damage: 0, range: 200 },
      { mpCost: 26, hpCost: 0, damage: 0, range: 250 },
      { mpCost: 25, hpCost: 0, damage: 0, range: 250 },
      { mpCost: 24, hpCost: 0, damage: 0, range: 250 },
      { mpCost: 23, hpCost: 0, damage: 0, range: 250 },
      { mpCost: 22, hpCost: 0, damage: 0, range: 250 },
      { mpCost: 21, hpCost: 0, damage: 0, range: 250 },
    ],
    prerequisite: null,
    buffEffect: null,
    buffDuration: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-monster-magnet',
    passiveEffect: null,
    mechanic: 'pull',
    maxTargets: 0,
    hpCostIsPercent: false,
    minHpPercent: 0,
  },

  // ═══ WARRIOR ACTIVE (Dragon Roar) ═══
  {
    id: 'warrior-dragon-roar',
    name: 'Dragon Roar',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Sacrifice a large portion of HP to attack up to 15 monsters within a large area. Temporarily stuns the Knight. Only usable above 50% HP.',
    maxLevel: 30,
    requiredCharacterLevel: 10,
    icon: '🐉',
    color: '#ff2200',
    scaling: {
      baseDamage: 0.96, damagePerLevel: 0.05,
      baseMpCost: 16, mpCostPerLevel: 0.5,
      baseCooldown: 6000, cooldownReductionPerLevel: 50,
      baseRange: 110, rangePerLevel: 10,
    },
    levelData: [
      { mpCost: 16, hpCost: 59, damage: 0.96, range: 110, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 58, damage: 1.02, range: 120, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 57, damage: 1.08, range: 130, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 56, damage: 1.14, range: 140, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 55, damage: 1.20, range: 150, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 54, damage: 1.26, range: 160, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 53, damage: 1.32, range: 170, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 52, damage: 1.38, range: 180, stunDurationMs: 4000 },
      { mpCost: 16, hpCost: 51, damage: 1.44, range: 190, stunDurationMs: 4000 },
      { mpCost: 24, hpCost: 50, damage: 1.50, range: 200, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 49, damage: 1.55, range: 210, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 48, damage: 1.60, range: 220, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 47, damage: 1.65, range: 230, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 46, damage: 1.70, range: 240, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 45, damage: 1.75, range: 250, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 44, damage: 1.80, range: 260, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 43, damage: 1.85, range: 270, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 42, damage: 1.90, range: 190, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 41, damage: 1.95, range: 290, stunDurationMs: 3000 },
      { mpCost: 24, hpCost: 40, damage: 2.00, range: 300, stunDurationMs: 3000 },
      { mpCost: 30, hpCost: 39, damage: 2.04, range: 310, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 38, damage: 2.08, range: 320, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 37, damage: 2.12, range: 330, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 36, damage: 2.16, range: 340, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 35, damage: 2.20, range: 350, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 34, damage: 2.24, range: 360, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 33, damage: 2.28, range: 370, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 32, damage: 2.32, range: 380, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 31, damage: 2.36, range: 390, stunDurationMs: 2000 },
      { mpCost: 30, hpCost: 30, damage: 2.40, range: 400, stunDurationMs: 2000 },
    ],
    prerequisite: { skillId: 'warrior-slash-blast', level: 5 },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 200,
    animationKey: 'warrior-dragon-roar',
    passiveEffect: null,
    mechanic: 'damage',
    maxTargets: 15,
    hpCostIsPercent: true,
    minHpPercent: 50,
  },
];

// ─── Default Key Bindings ────────────────────────

export const DEFAULT_KEY_BINDINGS: KeyBindings = {
  left: ['a', 'arrowleft'],
  right: ['d', 'arrowright'],
  up: ['w', 'arrowup'],
  down: ['s', 'arrowdown'],
  jump: [' '],
  attack: ['j'],
  skill1: ['1'],
  skill2: ['2'],
  skill3: ['3'],
  skill4: ['4'],
  skill5: ['5'],
  skill6: ['6'],
  openStats: ['p'],
  openSkills: ['o'],
  useHpPotion: ['7'],
  useMpPotion: ['8'],
  openShop: ['b'],
};

// ─── Shop Items ─────────────────────────────────

export const SHOP_ITEMS: ShopItemDefinition[] = [
  {
    id: 'shop-hp-potion',
    name: 'HP Potion',
    description: 'Restores 50 HP when used.',
    icon: '❤️',
    price: GAME_CONSTANTS.SHOP_HP_POTION_PRICE,
    type: DropType.HpPotion,
    value: GAME_CONSTANTS.HP_POTION_RESTORE,
  },
  {
    id: 'shop-mp-potion',
    name: 'MP Potion',
    description: 'Restores 30 MP when used.',
    icon: '💧',
    price: GAME_CONSTANTS.SHOP_MP_POTION_PRICE,
    type: DropType.MpPotion,
    value: GAME_CONSTANTS.MP_POTION_RESTORE,
  },
];
