import {
  CharacterClass,
  CharacterClassDefinition,
  CharacterStats,
} from './character';
import {
  ZombieType,
  ZombieDefinition,
} from './game-entities';
import { KeyBindings } from './messages';
import { SkillDefinition, SkillType } from './skill';

// ═══════════════════════════════════════════════════════════════
//  GAME CONSTANTS
//  Single source of truth for ALL tunable game variables.
//  Edit this file to adjust game balance, physics, combat, etc.
// ═══════════════════════════════════════════════════════════════

export const GAME_CONSTANTS = {

  // ─── Canvas & World ─────────────────────────────
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  GROUND_Y: 620,
  BACKGROUND_STAR_COUNT: 80,

  // ─── Physics ────────────────────────────────────
  GRAVITY: 0.5,
  TERMINAL_VELOCITY: 25,
  PLATFORM_SNAP_TOLERANCE: 6,

  // ─── Player Movement ────────────────────────────
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  PLAYER_JUMP_FORCE: -10,
  PLAYER_MOVE_SPEED: 5,
  PLAYER_FRICTION: .9,
  PLAYER_MIN_VELOCITY: 1,

  // ─── Player Combat ─────────────────────────────
  PLAYER_BASE_ATTACK_RANGE: 45,
  PLAYER_ATTACK_COOLDOWN_TICKS: 20,
  PLAYER_ATTACK_ANIM_MS: 200,
  PLAYER_SKILL_ANIM_MS: 300,
  INVINCIBILITY_FRAMES: 30,
  INVINCIBILITY_BLINK_RATE: 3,

  // ─── Knockback ──────────────────────────────────
  KNOCKBACK_FORCE_ZOMBIE: 8,
  KNOCKBACK_FORCE_PLAYER: 15,
  KNOCKBACK_UP_FORCE: -5,
  KNOCKBACK_ZOMBIE_FRAMES: 10,

  // ─── Player Derived Stat Formulas ───────────────
  PLAYER_BASE_HP: 50,
  PLAYER_BASE_MP: 30,
  PLAYER_SPEED_PER_DEX: 0.05,
  PLAYER_CRIT_RATE_CAP: 60,
  PLAYER_CRIT_DAMAGE_BASE: 150,

  // ─── XP & Leveling ─────────────────────────────
  XP_BASE: 80,
  XP_GROWTH: 1.4,
  STAT_POINTS_PER_LEVEL: 5,
  SKILL_POINTS_PER_LEVEL: 3,
  MAX_SKILL_LEVEL: 20,

  // ─── Waves ──────────────────────────────────────
  WAVE_ZOMBIE_COUNT_BASE: 5,
  WAVE_ZOMBIE_COUNT_GROWTH: 3,
  WAVE_TRANSITION_TICKS: 120,
  WAVE_INITIAL_SPAWN_DELAY_TICKS: 60,

  // ─── Zombie Spawning ───────────────────────────
  ZOMBIE_SPAWN_INTERVAL_MS: 2000,
  ZOMBIE_SPAWN_MIN_INTERVAL_MS: 500,
  ZOMBIE_SPAWN_DECREASE_PER_WAVE: 100,
  ZOMBIE_HP_SCALE_PER_WAVE: 0.15,
  ZOMBIE_RUNNER_MIN_WAVE: 2,
  ZOMBIE_RUNNER_ROLL_THRESHOLD: 0.7,
  ZOMBIE_TANK_MIN_WAVE: 3,
  ZOMBIE_TANK_ROLL_THRESHOLD: 0.85,
  ZOMBIE_SPITTER_MIN_WAVE: 4,
  ZOMBIE_SPITTER_ROLL_THRESHOLD: 0.6,
  ZOMBIE_BOSS_MIN_WAVE: 5,
  ZOMBIE_BOSS_WAVE_INTERVAL: 5,

  // ─── Zombie AI ────────────────────────────────
  ZOMBIE_JUMP_FORCE: -9,
  ZOMBIE_JUMP_COOLDOWN_MIN: 80,
  ZOMBIE_JUMP_COOLDOWN_MAX: 200,
  ZOMBIE_JUMP_CHANCE_PER_TICK: 0.015,
  ZOMBIE_JUMP_PLATFORM_CHASE_CHANCE: 0.04,
  ZOMBIE_ATTACK_RANGE: 35,
  ZOMBIE_ATTACK_COOLDOWN_MIN: 40,
  ZOMBIE_ATTACK_COOLDOWN_MAX: 70,
  ZOMBIE_ATTACK_ANIM_TICKS: 12,
  ZOMBIE_ATTACK_HIT_TICK: 6,
  ZOMBIE_CONTACT_DAMAGE_MULT: 0.3,

  // ─── Ropes ──────────────────────────────────────
  ROPE_CLIMB_SPEED: 5,
  ROPE_WIDTH: 6,
  ROPE_GRAB_RANGE: 20,

  // ─── Particles ──────────────────────────────────
  MAX_PARTICLES: 200,
  PARTICLE_LIFETIME_MS: 600,
  HIT_PARTICLE_COUNT: 6,
  HIT_PARTICLE_VELOCITY: 6,
  HIT_PARTICLE_UP_BIAS: 2,
  HIT_PARTICLE_LIFE: 30,
  DEATH_PARTICLE_COUNT: 15,
  DEATH_PARTICLE_VELOCITY: 10,
  DEATH_PARTICLE_UP_BIAS: 3,
  DEATH_PARTICLE_LIFE: 45,
  PARTICLE_GRAVITY: 0.15,

  // ─── Damage Numbers ────────────────────────────
  DAMAGE_NUMBER_LIFE_TICKS: 60,

  // ─── MP Potions ─────────────────────────────────
  MP_POTION_DROP_CHANCE: 0.30,
  MP_POTION_RESTORE_AMOUNT: 30,
  MP_POTION_LIFETIME: 600,
  MP_POTION_SIZE: 14,
  MP_POTION_POP_FORCE: -2,

  // ─── Tick Rate ──────────────────────────────────
  TICK_RATE: 50,

} as const;

// ─── Class Stat Weights (MapleStory-style) ──────

export interface ClassStatWeights {
  primaryStat: keyof CharacterStats;
  secondaryStat: keyof CharacterStats;
  attackFromPrimary: number;
  attackFromSecondary: number;
  defenseFromStr: number;
  defenseFromDex: number;
  hpPerStr: number;
  mpPerInt: number;
  critFromLuk: number;
  critDmgFromLuk: number;
}

export const CLASS_STAT_WEIGHTS: Record<CharacterClass, ClassStatWeights> = {
  [CharacterClass.Warrior]: {
    primaryStat: 'str',
    secondaryStat: 'dex',
    attackFromPrimary: 3.5,
    attackFromSecondary: 1.0,
    defenseFromStr: 1.5,
    defenseFromDex: 0.5,
    hpPerStr: 12,
    mpPerInt: 4,
    critFromLuk: 0.5,
    critDmgFromLuk: 1.0,
  },
  [CharacterClass.Ranger]: {
    primaryStat: 'dex',
    secondaryStat: 'str',
    attackFromPrimary: 3.5,
    attackFromSecondary: 1.0,
    defenseFromStr: 0.5,
    defenseFromDex: 1.0,
    hpPerStr: 8,
    mpPerInt: 6,
    critFromLuk: 1.0,
    critDmgFromLuk: 1.5,
  },
  [CharacterClass.Mage]: {
    primaryStat: 'int',
    secondaryStat: 'luk',
    attackFromPrimary: 4.0,
    attackFromSecondary: 0.5,
    defenseFromStr: 0.3,
    defenseFromDex: 0.3,
    hpPerStr: 6,
    mpPerInt: 14,
    critFromLuk: 1.0,
    critDmgFromLuk: 2.0,
  },
  [CharacterClass.Assassin]: {
    primaryStat: 'luk',
    secondaryStat: 'dex',
    attackFromPrimary: 3.0,
    attackFromSecondary: 1.5,
    defenseFromStr: 0.5,
    defenseFromDex: 1.0,
    hpPerStr: 7,
    mpPerInt: 5,
    critFromLuk: 2.0,
    critDmgFromLuk: 3.0,
  },
  [CharacterClass.Priest]: {
    primaryStat: 'int',
    secondaryStat: 'luk',
    attackFromPrimary: 3.5,
    attackFromSecondary: 0.8,
    defenseFromStr: 0.5,
    defenseFromDex: 0.5,
    hpPerStr: 8,
    mpPerInt: 12,
    critFromLuk: 0.8,
    critDmgFromLuk: 1.5,
  },
};

// ─── Character Classes ───────────────────────────

export const CHARACTER_CLASSES: Record<CharacterClass, CharacterClassDefinition> = {
  [CharacterClass.Warrior]: {
    id: CharacterClass.Warrior,
    name: 'Warrior',
    description: 'Heavy melee fighter with high HP and defense. Cleaves through zombie hordes.',
    baseStats: { str: 15, dex: 8, int: 4, luk: 6 },
    color: '#ff4444',
    icon: '⚔️',
  },
  [CharacterClass.Ranger]: {
    id: CharacterClass.Ranger,
    name: 'Ranger',
    description: 'Ranged attacker with high DEX. Picks off zombies from a safe distance.',
    baseStats: { str: 8, dex: 15, int: 6, luk: 8 },
    color: '#44cc44',
    icon: '🏹',
  },
  [CharacterClass.Mage]: {
    id: CharacterClass.Mage,
    name: 'Mage',
    description: 'Wields devastating AoE magic. Fragile but deals massive damage.',
    baseStats: { str: 4, dex: 6, int: 18, luk: 5 },
    color: '#6644ff',
    icon: '🔮',
  },
  [CharacterClass.Assassin]: {
    id: CharacterClass.Assassin,
    name: 'Assassin',
    description: 'Lightning-fast strikes and high crit chance. Thrives on lucky hits.',
    baseStats: { str: 10, dex: 12, int: 4, luk: 14 },
    color: '#cc44cc',
    icon: '🗡️',
  },
  [CharacterClass.Priest]: {
    id: CharacterClass.Priest,
    name: 'Priest',
    description: 'Support class that heals allies and smites undead with holy damage.',
    baseStats: { str: 6, dex: 6, int: 14, luk: 8 },
    color: '#ffcc44',
    icon: '✨',
  },
};

// ─── Zombie Types ────────────────────────────────

export const ZOMBIE_TYPES: Record<ZombieType, ZombieDefinition> = {
  [ZombieType.Walker]: {
    type: ZombieType.Walker,
    name: 'Walker',
    baseHp: 30,
    baseDamageMin: 30,
    baseDamageMax: 50,
    speed: 1,
    xpReward: 10,
    color: '#558833',
    width: 28,
    height: 40,
  },
  [ZombieType.Runner]: {
    type: ZombieType.Runner,
    name: 'Runner',
    baseHp: 20,
    baseDamageMin: 30,
    baseDamageMax: 50,
    speed: 3,
    xpReward: 15,
    color: '#886633',
    width: 24,
    height: 36,
  },
  [ZombieType.Tank]: {
    type: ZombieType.Tank,
    name: 'Tank',
    baseHp: 100,
    baseDamageMin: 10,
    baseDamageMax: 20,
    speed: 0.5,
    xpReward: 30,
    color: '#445522',
    width: 40,
    height: 48,
  },
  [ZombieType.Spitter]: {
    type: ZombieType.Spitter,
    name: 'Spitter',
    baseHp: 25,
    baseDamageMin: 8,
    baseDamageMax: 15,
    speed: 1.5,
    xpReward: 20,
    color: '#33aa55',
    width: 26,
    height: 38,
  },
  [ZombieType.Boss]: {
    type: ZombieType.Boss,
    name: 'Undead King',
    baseHp: 500,
    baseDamageMin: 25,
    baseDamageMax: 40,
    speed: 0.8,
    xpReward: 200,
    color: '#882222',
    width: 56,
    height: 64,
  },
};

// ─── Skills (10 per class, 50 total) ────────────

export const SKILLS: SkillDefinition[] = [
  // ═══ WARRIOR (STR-based, melee, tanky) ═══
  {
    id: 'warrior-power-strike',
    name: 'Power Strike',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Strong single-target melee hit.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '⚔️',
    color: '#ff4444',
    scaling: {
      baseDamage: 1.8,
      damagePerLevel: 0.18,
      baseMpCost: 8,
      mpCostPerLevel: 0.5,
      baseCooldown: 800,
      cooldownReductionPerLevel: 15,
      baseRange: 55,
      rangePerLevel: 1,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'warrior-power-strike',
  },
  {
    id: 'warrior-slash-blast',
    name: 'Slash Blast',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Wide arc slash hitting nearby enemies.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🌀',
    color: '#ff6644',
    scaling: {
      baseDamage: 1.4,
      damagePerLevel: 0.14,
      baseMpCost: 14,
      mpCostPerLevel: 0.6,
      baseCooldown: 1200,
      cooldownReductionPerLevel: 20,
      baseRange: 80,
      rangePerLevel: 2,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 80,
    animationKey: 'warrior-slash-blast',
  },
  {
    id: 'warrior-iron-body',
    name: 'Iron Body',
    classId: CharacterClass.Warrior,
    type: SkillType.Passive,
    description: 'Increases defense and max HP.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🛡️',
    color: '#888888',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'defense', baseValue: 5, valuePerLevel: 3 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-iron-body',
  },
  {
    id: 'warrior-war-leap',
    name: 'War Leap',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Dash forward dealing damage on contact.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '💨',
    color: '#ff8844',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.15,
      baseMpCost: 18,
      mpCostPerLevel: 0.7,
      baseCooldown: 2000,
      cooldownReductionPerLevel: 30,
      baseRange: 120,
      rangePerLevel: 3,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 40,
    animationKey: 'warrior-war-leap',
  },
  {
    id: 'warrior-weapon-mastery',
    name: 'Weapon Mastery',
    classId: CharacterClass.Warrior,
    type: SkillType.Passive,
    description: 'Increases minimum damage consistency.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '⚒️',
    color: '#ccaa44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'attack', baseValue: 3, valuePerLevel: 2 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-weapon-mastery',
  },
  {
    id: 'warrior-rage',
    name: 'Rage',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Temporary attack boost, costs HP.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🔥',
    color: '#ff2222',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 20,
      mpCostPerLevel: 0.8,
      baseCooldown: 8000,
      cooldownReductionPerLevel: 100,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-rage',
  },
  {
    id: 'warrior-ground-smash',
    name: 'Ground Smash',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'AoE shockwave around player.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '💥',
    color: '#aa6633',
    scaling: {
      baseDamage: 2.2,
      damagePerLevel: 0.22,
      baseMpCost: 28,
      mpCostPerLevel: 1.0,
      baseCooldown: 3500,
      cooldownReductionPerLevel: 40,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 120,
    animationKey: 'warrior-ground-smash',
  },
  {
    id: 'warrior-armor-crash',
    name: 'Armor Crash',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Debuff enemies, reducing their defense.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '🔨',
    color: '#996644',
    scaling: {
      baseDamage: 1.5,
      damagePerLevel: 0.12,
      baseMpCost: 22,
      mpCostPerLevel: 0.8,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 60,
      baseRange: 60,
      rangePerLevel: 2,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 60,
    animationKey: 'warrior-armor-crash',
  },
  {
    id: 'warrior-power-stance',
    name: 'Power Stance',
    classId: CharacterClass.Warrior,
    type: SkillType.Passive,
    description: 'Chance to resist knockback.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '🦶',
    color: '#886644',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'defense', baseValue: 3, valuePerLevel: 2 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-power-stance',
  },
  {
    id: 'warrior-valhalla',
    name: 'Valhalla',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Ultimate: massive damage + brief invincibility.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '⚡',
    color: '#ffaa00',
    scaling: {
      baseDamage: 4.0,
      damagePerLevel: 0.35,
      baseMpCost: 50,
      mpCostPerLevel: 1.5,
      baseCooldown: 15000,
      cooldownReductionPerLevel: 150,
      baseRange: 70,
      rangePerLevel: 2,
    },
    passiveBonus: null,
    hitCount: 3,
    aoeRadius: 100,
    animationKey: 'warrior-valhalla',
  },

  // ═══ RANGER (DEX-based, ranged) ═══
  {
    id: 'ranger-arrow-blow',
    name: 'Arrow Blow',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Quick single arrow shot.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '🏹',
    color: '#44cc44',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.16,
      baseMpCost: 6,
      mpCostPerLevel: 0.4,
      baseCooldown: 600,
      cooldownReductionPerLevel: 10,
      baseRange: 280,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'ranger-arrow-blow',
  },
  {
    id: 'ranger-double-shot',
    name: 'Double Shot',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Fire two arrows rapidly.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🎯',
    color: '#44ee44',
    scaling: {
      baseDamage: 1.2,
      damagePerLevel: 0.12,
      baseMpCost: 10,
      mpCostPerLevel: 0.5,
      baseCooldown: 900,
      cooldownReductionPerLevel: 15,
      baseRange: 280,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 2,
    aoeRadius: 0,
    animationKey: 'ranger-double-shot',
  },
  {
    id: 'ranger-critical-shot',
    name: 'Critical Shot',
    classId: CharacterClass.Ranger,
    type: SkillType.Passive,
    description: 'Increases crit rate for ranged attacks.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🎯',
    color: '#ffcc00',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'critRate', baseValue: 3, valuePerLevel: 1.5 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-critical-shot',
  },
  {
    id: 'ranger-arrow-bomb',
    name: 'Arrow Bomb',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Explosive arrow, AoE damage.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '💣',
    color: '#ff8844',
    scaling: {
      baseDamage: 1.8,
      damagePerLevel: 0.18,
      baseMpCost: 18,
      mpCostPerLevel: 0.7,
      baseCooldown: 2500,
      cooldownReductionPerLevel: 30,
      baseRange: 250,
      rangePerLevel: 4,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 90,
    animationKey: 'ranger-arrow-bomb',
  },
  {
    id: 'ranger-archery-mastery',
    name: 'Archery Mastery',
    classId: CharacterClass.Ranger,
    type: SkillType.Passive,
    description: 'Increases ranged damage consistency.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '🏹',
    color: '#88aa44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'attack', baseValue: 2, valuePerLevel: 2 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-archery-mastery',
  },
  {
    id: 'ranger-focus',
    name: 'Focus',
    classId: CharacterClass.Ranger,
    type: SkillType.Passive,
    description: 'Increases accuracy and avoidability.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '👁️',
    color: '#66cc88',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'speed', baseValue: 0.2, valuePerLevel: 0.1 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-focus',
  },
  {
    id: 'ranger-arrow-rain',
    name: 'Arrow Rain',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Arrows fall from sky in a zone.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🌧️',
    color: '#44aacc',
    scaling: {
      baseDamage: 1.5,
      damagePerLevel: 0.15,
      baseMpCost: 28,
      mpCostPerLevel: 1.0,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 60,
      baseRange: 250,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 3,
    aoeRadius: 120,
    animationKey: 'ranger-arrow-rain',
  },
  {
    id: 'ranger-strafe',
    name: 'Strafe',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Rapid 4-hit combo on single target.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '⚡',
    color: '#44ff88',
    scaling: {
      baseDamage: 1.0,
      damagePerLevel: 0.10,
      baseMpCost: 22,
      mpCostPerLevel: 0.8,
      baseCooldown: 1800,
      cooldownReductionPerLevel: 25,
      baseRange: 300,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 4,
    aoeRadius: 0,
    animationKey: 'ranger-strafe',
  },
  {
    id: 'ranger-evasion-boost',
    name: 'Evasion Boost',
    classId: CharacterClass.Ranger,
    type: SkillType.Passive,
    description: 'Dodge chance + speed bonus.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '💨',
    color: '#88ff88',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'speed', baseValue: 0.3, valuePerLevel: 0.15 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-evasion-boost',
  },
  {
    id: 'ranger-hurricane',
    name: 'Hurricane',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Ultimate: rapid-fire stream of arrows.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '🌪️',
    color: '#22ff44',
    scaling: {
      baseDamage: 0.8,
      damagePerLevel: 0.10,
      baseMpCost: 45,
      mpCostPerLevel: 1.5,
      baseCooldown: 12000,
      cooldownReductionPerLevel: 150,
      baseRange: 320,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 8,
    aoeRadius: 0,
    animationKey: 'ranger-hurricane',
  },

  // ═══ MAGE (INT-based, AoE magic) ═══
  {
    id: 'mage-energy-bolt',
    name: 'Energy Bolt',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Basic magic projectile.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '🔮',
    color: '#6644ff',
    scaling: {
      baseDamage: 1.7,
      damagePerLevel: 0.17,
      baseMpCost: 8,
      mpCostPerLevel: 0.4,
      baseCooldown: 700,
      cooldownReductionPerLevel: 10,
      baseRange: 220,
      rangePerLevel: 4,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'mage-energy-bolt',
  },
  {
    id: 'mage-fireball',
    name: 'Fireball',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Fireball with splash damage.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🔥',
    color: '#ff6622',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 15,
      mpCostPerLevel: 0.6,
      baseCooldown: 1500,
      cooldownReductionPerLevel: 20,
      baseRange: 200,
      rangePerLevel: 4,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 70,
    animationKey: 'mage-fireball',
  },
  {
    id: 'mage-mp-boost',
    name: 'MP Boost',
    classId: CharacterClass.Mage,
    type: SkillType.Passive,
    description: 'Increases max MP and MP regen.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '💧',
    color: '#4488ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'maxMp', baseValue: 10, valuePerLevel: 5 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-mp-boost',
  },
  {
    id: 'mage-ice-beam',
    name: 'Ice Beam',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Freezing projectile, slows enemies.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '❄️',
    color: '#88ccff',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.16,
      baseMpCost: 16,
      mpCostPerLevel: 0.6,
      baseCooldown: 1800,
      cooldownReductionPerLevel: 25,
      baseRange: 240,
      rangePerLevel: 4,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'mage-ice-beam',
  },
  {
    id: 'mage-spell-mastery',
    name: 'Spell Mastery',
    classId: CharacterClass.Mage,
    type: SkillType.Passive,
    description: 'Increases magic damage consistency.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '📖',
    color: '#aa66ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'attack', baseValue: 3, valuePerLevel: 2.5 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-spell-mastery',
  },
  {
    id: 'mage-teleport',
    name: 'Teleport',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Short-range blink.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '✨',
    color: '#cc88ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 12,
      mpCostPerLevel: 0.3,
      baseCooldown: 2000,
      cooldownReductionPerLevel: 30,
      baseRange: 150,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-teleport',
  },
  {
    id: 'mage-chain-lightning',
    name: 'Chain Lightning',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Lightning bounces between enemies.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '⚡',
    color: '#ffff44',
    scaling: {
      baseDamage: 2.2,
      damagePerLevel: 0.22,
      baseMpCost: 30,
      mpCostPerLevel: 1.0,
      baseCooldown: 3000,
      cooldownReductionPerLevel: 40,
      baseRange: 200,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 4,
    aoeRadius: 0,
    animationKey: 'mage-chain-lightning',
  },
  {
    id: 'mage-meteor-shower',
    name: 'Meteor Shower',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Massive AoE fire from sky.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '☄️',
    color: '#ff4400',
    scaling: {
      baseDamage: 3.5,
      damagePerLevel: 0.30,
      baseMpCost: 45,
      mpCostPerLevel: 1.5,
      baseCooldown: 8000,
      cooldownReductionPerLevel: 100,
      baseRange: 200,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 3,
    aoeRadius: 150,
    animationKey: 'mage-meteor-shower',
  },
  {
    id: 'mage-magic-guard',
    name: 'Magic Guard',
    classId: CharacterClass.Mage,
    type: SkillType.Passive,
    description: 'Portion of damage taken from MP instead.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '🛡️',
    color: '#8888ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'defense', baseValue: 4, valuePerLevel: 2 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-magic-guard',
  },
  {
    id: 'mage-infinity',
    name: 'Infinity',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Ultimate: unlimited MP + damage boost for duration.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '♾️',
    color: '#aa44ff',
    scaling: {
      baseDamage: 1.5,
      damagePerLevel: 0.15,
      baseMpCost: 60,
      mpCostPerLevel: 1.5,
      baseCooldown: 18000,
      cooldownReductionPerLevel: 200,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-infinity',
  },

  // ═══ ASSASSIN (LUK-based, fast melee + thrown) ═══
  {
    id: 'assassin-lucky-seven',
    name: 'Lucky Seven',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Throw two quick projectiles.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '⭐',
    color: '#cc44cc',
    scaling: {
      baseDamage: 1.3,
      damagePerLevel: 0.13,
      baseMpCost: 6,
      mpCostPerLevel: 0.3,
      baseCooldown: 500,
      cooldownReductionPerLevel: 8,
      baseRange: 200,
      rangePerLevel: 4,
    },
    passiveBonus: null,
    hitCount: 2,
    aoeRadius: 0,
    animationKey: 'assassin-lucky-seven',
  },
  {
    id: 'assassin-shadow-strike',
    name: 'Shadow Strike',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Dash-strike with high crit chance.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '💨',
    color: '#aa33aa',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 12,
      mpCostPerLevel: 0.5,
      baseCooldown: 1000,
      cooldownReductionPerLevel: 15,
      baseRange: 60,
      rangePerLevel: 2,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'assassin-shadow-strike',
  },
  {
    id: 'assassin-nimble-body',
    name: 'Nimble Body',
    classId: CharacterClass.Assassin,
    type: SkillType.Passive,
    description: 'Increases speed and avoidability.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🦶',
    color: '#ee88ee',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'speed', baseValue: 0.3, valuePerLevel: 0.15 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-nimble-body',
  },
  {
    id: 'assassin-dark-sight',
    name: 'Dark Sight',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Brief invisibility, next attack crits.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '👁️',
    color: '#442244',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 14,
      mpCostPerLevel: 0.4,
      baseCooldown: 6000,
      cooldownReductionPerLevel: 80,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-dark-sight',
  },
  {
    id: 'assassin-dagger-mastery',
    name: 'Dagger Mastery',
    classId: CharacterClass.Assassin,
    type: SkillType.Passive,
    description: 'Increases min damage with daggers.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '🗡️',
    color: '#cc88cc',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'attack', baseValue: 2, valuePerLevel: 1.5 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-dagger-mastery',
  },
  {
    id: 'assassin-haste',
    name: 'Haste',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Temporarily boosts speed and jump.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '⚡',
    color: '#ff88ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 16,
      mpCostPerLevel: 0.5,
      baseCooldown: 8000,
      cooldownReductionPerLevel: 100,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-haste',
  },
  {
    id: 'assassin-savage-blow',
    name: 'Savage Blow',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Rapid 6-hit combo attack.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🔪',
    color: '#dd44dd',
    scaling: {
      baseDamage: 0.8,
      damagePerLevel: 0.08,
      baseMpCost: 24,
      mpCostPerLevel: 0.8,
      baseCooldown: 2000,
      cooldownReductionPerLevel: 25,
      baseRange: 50,
      rangePerLevel: 1,
    },
    passiveBonus: null,
    hitCount: 6,
    aoeRadius: 0,
    animationKey: 'assassin-savage-blow',
  },
  {
    id: 'assassin-shadow-partner',
    name: 'Shadow Partner',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Summon shadow that mimics attacks.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '👥',
    color: '#6622aa',
    scaling: {
      baseDamage: 0.6,
      damagePerLevel: 0.06,
      baseMpCost: 30,
      mpCostPerLevel: 1.0,
      baseCooldown: 10000,
      cooldownReductionPerLevel: 120,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-shadow-partner',
  },
  {
    id: 'assassin-venomous-stab',
    name: 'Venomous Stab',
    classId: CharacterClass.Assassin,
    type: SkillType.Passive,
    description: 'Attacks have chance to poison.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '☠️',
    color: '#44aa44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'allDamagePercent', baseValue: 2, valuePerLevel: 1.5 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-venomous-stab',
  },
  {
    id: 'assassin-assassinate',
    name: 'Assassinate',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Ultimate: massive single-target burst.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '💀',
    color: '#880088',
    scaling: {
      baseDamage: 5.0,
      damagePerLevel: 0.40,
      baseMpCost: 50,
      mpCostPerLevel: 1.5,
      baseCooldown: 14000,
      cooldownReductionPerLevel: 150,
      baseRange: 55,
      rangePerLevel: 1,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'assassin-assassinate',
  },

  // ═══ PRIEST (INT-based, support + holy) ═══
  {
    id: 'priest-holy-arrow',
    name: 'Holy Arrow',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Light projectile, bonus vs undead.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '☀️',
    color: '#ffcc44',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.16,
      baseMpCost: 8,
      mpCostPerLevel: 0.4,
      baseCooldown: 800,
      cooldownReductionPerLevel: 12,
      baseRange: 200,
      rangePerLevel: 4,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'priest-holy-arrow',
  },
  {
    id: 'priest-heal',
    name: 'Heal',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Restore HP to self and nearby allies.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '💚',
    color: '#44ff88',
    scaling: {
      baseDamage: -1.5,
      damagePerLevel: -0.15,
      baseMpCost: 20,
      mpCostPerLevel: 0.8,
      baseCooldown: 3000,
      cooldownReductionPerLevel: 40,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 120,
    animationKey: 'priest-heal',
  },
  {
    id: 'priest-bless',
    name: 'Bless',
    classId: CharacterClass.Priest,
    type: SkillType.Passive,
    description: 'Increases all stats slightly.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '✨',
    color: '#ffeeaa',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'attack', baseValue: 2, valuePerLevel: 1 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-bless',
  },
  {
    id: 'priest-holy-symbol',
    name: 'Holy Symbol',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Temporary XP boost for party.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '🔆',
    color: '#ffdd66',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 30,
      mpCostPerLevel: 1.0,
      baseCooldown: 12000,
      cooldownReductionPerLevel: 150,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 0,
    aoeRadius: 200,
    animationKey: 'priest-holy-symbol',
  },
  {
    id: 'priest-spell-mastery',
    name: 'Spell Mastery',
    classId: CharacterClass.Priest,
    type: SkillType.Passive,
    description: 'Increases magic damage consistency.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '📖',
    color: '#ccaa66',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'attack', baseValue: 2, valuePerLevel: 2 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-spell-mastery',
  },
  {
    id: 'priest-invincible',
    name: 'Invincible',
    classId: CharacterClass.Priest,
    type: SkillType.Passive,
    description: 'Reduces incoming damage by flat amount.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '🛡️',
    color: '#ffcc88',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'defense', baseValue: 4, valuePerLevel: 2.5 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-invincible',
  },
  {
    id: 'priest-shining-ray',
    name: 'Shining Ray',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Beam of light hitting enemies in a line.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🌟',
    color: '#ffffaa',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 25,
      mpCostPerLevel: 0.8,
      baseCooldown: 2500,
      cooldownReductionPerLevel: 30,
      baseRange: 250,
      rangePerLevel: 5,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 30,
    animationKey: 'priest-shining-ray',
  },
  {
    id: 'priest-dispel',
    name: 'Dispel',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Remove debuffs, damage undead in area.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '💫',
    color: '#eedd88',
    scaling: {
      baseDamage: 1.4,
      damagePerLevel: 0.14,
      baseMpCost: 22,
      mpCostPerLevel: 0.7,
      baseCooldown: 4000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 100,
    animationKey: 'priest-dispel',
  },
  {
    id: 'priest-holy-shield',
    name: 'Holy Shield',
    classId: CharacterClass.Priest,
    type: SkillType.Passive,
    description: 'Chance to block incoming damage entirely.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '✝️',
    color: '#ffee44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 0,
      mpCostPerLevel: 0,
      baseCooldown: 0,
      cooldownReductionPerLevel: 0,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: { stat: 'defense', baseValue: 5, valuePerLevel: 3 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-holy-shield',
  },
  {
    id: 'priest-genesis',
    name: 'Genesis',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Ultimate: massive holy AoE, heals allies.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '🌅',
    color: '#ffff88',
    scaling: {
      baseDamage: 3.5,
      damagePerLevel: 0.30,
      baseMpCost: 55,
      mpCostPerLevel: 1.5,
      baseCooldown: 16000,
      cooldownReductionPerLevel: 180,
      baseRange: 0,
      rangePerLevel: 0,
    },
    passiveBonus: null,
    hitCount: 1,
    aoeRadius: 180,
    animationKey: 'priest-genesis',
  },
];

// ─── Default Key Bindings ────────────────────────

export const DEFAULT_KEY_BINDINGS: KeyBindings = {
  left: ['a', 'arrowleft'],
  right: ['d', 'arrowright'],
  up: ['w', 'arrowup'],
  down: ['s', 'arrowdown'],
  jump: [' '],
  attack: ['j'],
  skill1: ['1'],
  skill2: ['2'],
  skill3: ['3'],
  skill4: ['4'],
  skill5: ['5'],
  skill6: ['6'],
  openStats: ['p'],
  openSkills: ['o'],
};
