import {
  CharacterClass,
  CharacterClassDefinition,
  CharacterStats,
} from './character';
import {
  ZombieType,
  ZombieDefinition,
  DropType,
  ShopItemDefinition,
} from './game-entities';
import { KeyBindings } from './messages';
import { SkillDefinition, SkillType } from './skill';

// ═══════════════════════════════════════════════════════════════
//  GAME CONSTANTS
//  Single source of truth for ALL tunable game variables.
//  Edit this file to adjust game balance, physics, combat, etc.
// ═══════════════════════════════════════════════════════════════

export const GAME_CONSTANTS = {

  // ─── Canvas & World ─────────────────────────────
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  GROUND_Y: 620,
  BACKGROUND_STAR_COUNT: 80,

  // ─── Physics ────────────────────────────────────
  GRAVITY: 0.5,
  TERMINAL_VELOCITY: 25,
  PLATFORM_SNAP_TOLERANCE: 6,

  // ─── Player Movement ────────────────────────────
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  PLAYER_JUMP_FORCE: -10,
  PLAYER_MOVE_SPEED: 5,
  PLAYER_FRICTION: .9,
  PLAYER_AIR_CONTROL: 0.7,
  PLAYER_MIN_VELOCITY: 1,

  // ─── Player Combat ─────────────────────────────
  PLAYER_BASE_ATTACK_RANGE: 50,
  PLAYER_ATTACK_COOLDOWN_TICKS: 24,
  PLAYER_ATTACK_ANIM_MS: 480,
  PLAYER_ATTACK_HIT_DELAY_MS: 240,
  PLAYER_SKILL_ANIM_MS: 480,
  INVINCIBILITY_FRAMES: 90,
  INVINCIBILITY_BLINK_RATE: 3,

  // ─── Knockback ──────────────────────────────────
  KNOCKBACK_FORCE_ZOMBIE: 8,
  KNOCKBACK_FORCE_PLAYER: 15,
  KNOCKBACK_UP_FORCE: -5,
  KNOCKBACK_ZOMBIE_FRAMES: 10,

  // ─── Player Derived Stat Formulas ───────────────
  PLAYER_BASE_HP: 50,
  PLAYER_BASE_MP: 30,
  PLAYER_SPEED_PER_DEX: 0.05,
  PLAYER_CRIT_RATE_CAP: 60,
  PLAYER_CRIT_DAMAGE_BASE: 150,

  // ─── XP & Leveling ─────────────────────────────
  XP_BASE: 80,
  XP_GROWTH: 1.4,
  STAT_POINTS_PER_LEVEL: 5,
  SKILL_POINTS_PER_LEVEL: 3,
  MAX_SKILL_LEVEL: 20,

  // ─── Waves ──────────────────────────────────────
  WAVE_ZOMBIE_COUNT_BASE: 5,
  WAVE_ZOMBIE_COUNT_GROWTH: 3,
  WAVE_TRANSITION_TICKS: 120,
  WAVE_INITIAL_SPAWN_DELAY_TICKS: 60,

  // ─── Zombie Spawning ───────────────────────────
  ZOMBIE_SPAWN_INTERVAL_MS: 2000,
  ZOMBIE_SPAWN_MIN_INTERVAL_MS: 500,
  ZOMBIE_SPAWN_DECREASE_PER_WAVE: 100,
  ZOMBIE_HP_SCALE_PER_WAVE: 0.15,
  ZOMBIE_RUNNER_MIN_WAVE: 2,
  ZOMBIE_RUNNER_ROLL_THRESHOLD: 0.7,
  ZOMBIE_TANK_MIN_WAVE: 3,
  ZOMBIE_TANK_ROLL_THRESHOLD: 0.85,
  ZOMBIE_SPITTER_MIN_WAVE: 4,
  ZOMBIE_SPITTER_ROLL_THRESHOLD: 0.6,
  ZOMBIE_BOSS_MIN_WAVE: 5,
  ZOMBIE_BOSS_WAVE_INTERVAL: 5,

  // ─── Zombie AI ────────────────────────────────
  ZOMBIE_ORBIT_MIN: 25,
  ZOMBIE_ORBIT_MAX: 55,
  ZOMBIE_ORBIT_ARRIVE_THRESHOLD: 15,
  ZOMBIE_JUMP_FORCE: -9,
  ZOMBIE_JUMP_COOLDOWN_MIN: 80,
  ZOMBIE_JUMP_COOLDOWN_MAX: 200,
  ZOMBIE_JUMP_CHANCE_PER_TICK: 0.015,
  ZOMBIE_JUMP_PLATFORM_CHASE_CHANCE: 0.04,
  ZOMBIE_ATTACK_RANGE: 35,
  ZOMBIE_ATTACK_COOLDOWN_MIN: 40,
  ZOMBIE_ATTACK_COOLDOWN_MAX: 70,
  ZOMBIE_ATTACK_ANIM_TICKS: 12,
  ZOMBIE_ATTACK_HIT_TICK: 6,
  ZOMBIE_CONTACT_DAMAGE_MULT: 0.3,

  // ─── Ropes ──────────────────────────────────────
  ROPE_CLIMB_SPEED: 5,
  ROPE_WIDTH: 6,
  ROPE_GRAB_RANGE: 20,

  // ─── Particles ──────────────────────────────────
  MAX_PARTICLES: 200,
  PARTICLE_LIFETIME_MS: 600,
  HIT_PARTICLE_COUNT: 6,
  HIT_PARTICLE_VELOCITY: 6,
  HIT_PARTICLE_UP_BIAS: 2,
  HIT_PARTICLE_LIFE: 30,
  DEATH_PARTICLE_COUNT: 15,
  DEATH_PARTICLE_VELOCITY: 10,
  DEATH_PARTICLE_UP_BIAS: 3,
  DEATH_PARTICLE_LIFE: 45,
  PARTICLE_GRAVITY: 0.15,

  // ─── Damage Numbers ────────────────────────────
  DAMAGE_NUMBER_LIFE_TICKS: 60,

  // ─── Drop Rates ───────────────────────────────
  DROP_HP_POTION_CHANCE: 0.08,
  DROP_MP_POTION_CHANCE: 0.10,
  DROP_GOLD_CHANCE: 0.55,
  DROP_GOLD_MIN: 5,
  DROP_GOLD_MAX: 25,
  DROP_GOLD_WAVE_BONUS: 3,
  DROP_LIFETIME: 600,
  DROP_SIZE: 14,
  DROP_POP_FORCE: -2,

  // ─── Potions ──────────────────────────────────
  HP_POTION_RESTORE: 50,
  MP_POTION_RESTORE: 30,
  POTION_USE_COOLDOWN_TICKS: 30,

  // ─── Shop ────────────────────────────────────
  SHOP_HP_POTION_PRICE: 30,
  SHOP_MP_POTION_PRICE: 20,

  // ─── Tick Rate ──────────────────────────────────
  TICK_RATE: 50,

} as const;

// ─── Class Stat Weights (MapleStory-style) ──────

export interface ClassStatWeights {
  primaryStat: keyof CharacterStats;
  secondaryStat: keyof CharacterStats;
  attackFromPrimary: number;
  attackFromSecondary: number;
  defenseFromStr: number;
  defenseFromDex: number;
  hpPerStr: number;
  mpPerInt: number;
  critFromLuk: number;
  critDmgFromLuk: number;
}

export const CLASS_STAT_WEIGHTS: Record<CharacterClass, ClassStatWeights> = {
  [CharacterClass.Warrior]: {
    primaryStat: 'str',
    secondaryStat: 'dex',
    attackFromPrimary: 3.5,
    attackFromSecondary: 1.0,
    defenseFromStr: 1.5,
    defenseFromDex: 0.5,
    hpPerStr: 12,
    mpPerInt: 4,
    critFromLuk: 0.5,
    critDmgFromLuk: 1.0,
  },
  [CharacterClass.Ranger]: {
    primaryStat: 'dex',
    secondaryStat: 'str',
    attackFromPrimary: 3.5,
    attackFromSecondary: 1.0,
    defenseFromStr: 0.5,
    defenseFromDex: 1.0,
    hpPerStr: 8,
    mpPerInt: 6,
    critFromLuk: 1.0,
    critDmgFromLuk: 1.5,
  },
  [CharacterClass.Mage]: {
    primaryStat: 'int',
    secondaryStat: 'luk',
    attackFromPrimary: 4.0,
    attackFromSecondary: 0.5,
    defenseFromStr: 0.3,
    defenseFromDex: 0.3,
    hpPerStr: 6,
    mpPerInt: 14,
    critFromLuk: 1.0,
    critDmgFromLuk: 2.0,
  },
  [CharacterClass.Assassin]: {
    primaryStat: 'luk',
    secondaryStat: 'dex',
    attackFromPrimary: 3.0,
    attackFromSecondary: 1.5,
    defenseFromStr: 0.5,
    defenseFromDex: 1.0,
    hpPerStr: 7,
    mpPerInt: 5,
    critFromLuk: 2.0,
    critDmgFromLuk: 3.0,
  },
  [CharacterClass.Priest]: {
    primaryStat: 'int',
    secondaryStat: 'luk',
    attackFromPrimary: 3.5,
    attackFromSecondary: 0.8,
    defenseFromStr: 0.5,
    defenseFromDex: 0.5,
    hpPerStr: 8,
    mpPerInt: 12,
    critFromLuk: 0.8,
    critDmgFromLuk: 1.5,
  },
};

// ─── Character Classes ───────────────────────────

export const CHARACTER_CLASSES: Record<CharacterClass, CharacterClassDefinition> = {
  [CharacterClass.Warrior]: {
    id: CharacterClass.Warrior,
    name: 'Warrior',
    description: 'Heavy melee fighter with high HP and defense. Cleaves through zombie hordes.',
    baseStats: { str: 15, dex: 8, int: 4, luk: 6 },
    color: '#ff4444',
    icon: '⚔️',
  },
  [CharacterClass.Ranger]: {
    id: CharacterClass.Ranger,
    name: 'Ranger',
    description: 'Ranged attacker with high DEX. Picks off zombies from a safe distance.',
    baseStats: { str: 8, dex: 15, int: 6, luk: 8 },
    color: '#44cc44',
    icon: '🏹',
  },
  [CharacterClass.Mage]: {
    id: CharacterClass.Mage,
    name: 'Mage',
    description: 'Wields devastating AoE magic. Fragile but deals massive damage.',
    baseStats: { str: 4, dex: 6, int: 18, luk: 5 },
    color: '#6644ff',
    icon: '🔮',
  },
  [CharacterClass.Assassin]: {
    id: CharacterClass.Assassin,
    name: 'Assassin',
    description: 'Lightning-fast strikes and high crit chance. Thrives on lucky hits.',
    baseStats: { str: 10, dex: 12, int: 4, luk: 14 },
    color: '#cc44cc',
    icon: '🗡️',
  },
  [CharacterClass.Priest]: {
    id: CharacterClass.Priest,
    name: 'Priest',
    description: 'Support class that heals allies and smites undead with holy damage.',
    baseStats: { str: 6, dex: 6, int: 14, luk: 8 },
    color: '#ffcc44',
    icon: '✨',
  },
};

// ─── Zombie Types ────────────────────────────────

export const ZOMBIE_TYPES: Record<ZombieType, ZombieDefinition> = {
  [ZombieType.Walker]: {
    type: ZombieType.Walker,
    name: 'Walker',
    baseHp: 30,
    baseDamageMin: 30,
    baseDamageMax: 50,
    speed: 1,
    xpReward: 10,
    color: '#558833',
    width: 28,
    height: 40,
  },
  [ZombieType.Runner]: {
    type: ZombieType.Runner,
    name: 'Runner',
    baseHp: 20,
    baseDamageMin: 30,
    baseDamageMax: 50,
    speed: 3,
    xpReward: 15,
    color: '#886633',
    width: 24,
    height: 36,
  },
  [ZombieType.Tank]: {
    type: ZombieType.Tank,
    name: 'Tank',
    baseHp: 100,
    baseDamageMin: 10,
    baseDamageMax: 20,
    speed: 0.5,
    xpReward: 30,
    color: '#445522',
    width: 40,
    height: 48,
  },
  [ZombieType.Spitter]: {
    type: ZombieType.Spitter,
    name: 'Spitter',
    baseHp: 25,
    baseDamageMin: 8,
    baseDamageMax: 15,
    speed: 1.5,
    xpReward: 20,
    color: '#33aa55',
    width: 26,
    height: 38,
  },
  [ZombieType.Boss]: {
    type: ZombieType.Boss,
    name: 'Undead King',
    baseHp: 500,
    baseDamageMin: 25,
    baseDamageMax: 40,
    speed: 0.8,
    xpReward: 200,
    color: '#882222',
    width: 56,
    height: 64,
  },
};

// ─── Skills (10 per class, 50 total) ────────────
// Buff duration: 60s at level 1, scaling to ~120s at level 20.
// All former "passive" skills are now activated buffs with duration.

export const SKILLS: SkillDefinition[] = [
  // ═══ WARRIOR (STR-based, melee, tanky) ═══
  {
    id: 'warrior-power-strike',
    name: 'Power Strike',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Concentrates power into a single devastating sword strike. One of the first skills a Warrior learns.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '⚔️',
    color: '#ff4444',
    scaling: {
      baseDamage: 1.8,
      damagePerLevel: 0.18,
      baseMpCost: 8,
      mpCostPerLevel: 0.5,
      baseCooldown: 800,
      cooldownReductionPerLevel: 15,
      baseRange: 55,
      rangePerLevel: 1,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'warrior-power-strike',
  },
  {
    id: 'warrior-slash-blast',
    name: 'Slash Blast',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Swings weapon in a wide arc, slashing up to 6 nearby enemies with a powerful wave of energy.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🌀',
    color: '#ff6644',
    scaling: {
      baseDamage: 1.4,
      damagePerLevel: 0.14,
      baseMpCost: 14,
      mpCostPerLevel: 0.6,
      baseCooldown: 1200,
      cooldownReductionPerLevel: 20,
      baseRange: 80,
      rangePerLevel: 2,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 80,
    animationKey: 'warrior-slash-blast',
  },
  {
    id: 'warrior-iron-body',
    name: 'Iron Body',
    classId: CharacterClass.Warrior,
    type: SkillType.Buff,
    description: 'Temporarily hardens the body like iron, increasing weapon defense. A staple defensive buff for Warriors.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🛡️',
    color: '#888888',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 10,
      mpCostPerLevel: 0.4,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'defense', baseValue: 5, valuePerLevel: 3 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-iron-body',
  },
  {
    id: 'warrior-war-leap',
    name: 'War Leap',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Charges forward at high speed, smashing through enemies in the path. Useful for gap-closing.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '💨',
    color: '#ff8844',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.15,
      baseMpCost: 18,
      mpCostPerLevel: 0.7,
      baseCooldown: 2000,
      cooldownReductionPerLevel: 30,
      baseRange: 120,
      rangePerLevel: 3,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 40,
    animationKey: 'warrior-war-leap',
  },
  {
    id: 'warrior-weapon-mastery',
    name: 'Weapon Mastery',
    classId: CharacterClass.Warrior,
    type: SkillType.Buff,
    description: 'Activates mastery training, increasing weapon attack and damage stability for the duration.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '⚒️',
    color: '#ccaa44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 8,
      mpCostPerLevel: 0.3,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'attack', baseValue: 3, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-weapon-mastery',
  },
  {
    id: 'warrior-rage',
    name: 'Rage',
    classId: CharacterClass.Warrior,
    type: SkillType.Buff,
    description: 'Enters a berserker rage, boosting weapon attack at the cost of reduced defense. Affects nearby party members.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🔥',
    color: '#ff2222',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 16,
      mpCostPerLevel: 0.6,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'attack', baseValue: 8, valuePerLevel: 3 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-rage',
  },
  {
    id: 'warrior-ground-smash',
    name: 'Ground Smash',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Slams weapon into the ground, creating a shockwave that damages up to 4 enemies in the area.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '💥',
    color: '#aa6633',
    scaling: {
      baseDamage: 2.2,
      damagePerLevel: 0.22,
      baseMpCost: 28,
      mpCostPerLevel: 1.0,
      baseCooldown: 3500,
      cooldownReductionPerLevel: 40,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 120,
    animationKey: 'warrior-ground-smash',
  },
  {
    id: 'warrior-armor-crash',
    name: 'Armor Crash',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Strikes enemies with a shattering blow that strips their defensive buffs and temporarily weakens them.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '🔨',
    color: '#996644',
    scaling: {
      baseDamage: 1.5,
      damagePerLevel: 0.12,
      baseMpCost: 22,
      mpCostPerLevel: 0.8,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 60,
      baseRange: 60,
      rangePerLevel: 2,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 60,
    animationKey: 'warrior-armor-crash',
  },
  {
    id: 'warrior-power-stance',
    name: 'Power Stance',
    classId: CharacterClass.Warrior,
    type: SkillType.Buff,
    description: 'Plants feet firmly, granting a chance to resist knockback from enemy attacks. Essential for tanking.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '🦶',
    color: '#886644',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 12,
      mpCostPerLevel: 0.5,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'defense', baseValue: 3, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'warrior-power-stance',
  },
  {
    id: 'warrior-brandish',
    name: 'Brandish',
    classId: CharacterClass.Warrior,
    type: SkillType.Active,
    description: 'Performs a devastating double slash, hitting up to 3 enemies with two rapid strikes. The Warrior\'s ultimate technique.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '⚡',
    color: '#ffaa00',
    scaling: {
      baseDamage: 4.0,
      damagePerLevel: 0.35,
      baseMpCost: 50,
      mpCostPerLevel: 1.5,
      baseCooldown: 15000,
      cooldownReductionPerLevel: 150,
      baseRange: 70,
      rangePerLevel: 2,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 3,
    aoeRadius: 100,
    animationKey: 'warrior-brandish',
  },

  // ═══ RANGER (DEX-based, ranged) ═══
  {
    id: 'ranger-arrow-blow',
    name: 'Arrow Blow',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Fires consecutive arrows at enemies in front. A basic but reliable Archer attack skill.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '🏹',
    color: '#44cc44',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.16,
      baseMpCost: 6,
      mpCostPerLevel: 0.4,
      baseCooldown: 600,
      cooldownReductionPerLevel: 10,
      baseRange: 280,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'ranger-arrow-blow',
  },
  {
    id: 'ranger-double-shot',
    name: 'Double Shot',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Rapidly fires two arrows in quick succession. Higher average damage than Arrow Blow.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🎯',
    color: '#44ee44',
    scaling: {
      baseDamage: 1.2,
      damagePerLevel: 0.12,
      baseMpCost: 10,
      mpCostPerLevel: 0.5,
      baseCooldown: 900,
      cooldownReductionPerLevel: 15,
      baseRange: 280,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 2,
    aoeRadius: 0,
    animationKey: 'ranger-double-shot',
  },
  {
    id: 'ranger-critical-shot',
    name: 'Critical Shot',
    classId: CharacterClass.Ranger,
    type: SkillType.Buff,
    description: 'Sharpens focus to increase critical hit rate for all ranged attacks. A must-have for Bowmen.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🎯',
    color: '#ffcc00',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 8,
      mpCostPerLevel: 0.3,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'critRate', baseValue: 3, valuePerLevel: 1.5 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-critical-shot',
  },
  {
    id: 'ranger-arrow-bomb',
    name: 'Arrow Bomb',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Fires an explosive arrow that detonates on impact, dealing splash damage to nearby enemies.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '💣',
    color: '#ff8844',
    scaling: {
      baseDamage: 1.8,
      damagePerLevel: 0.18,
      baseMpCost: 18,
      mpCostPerLevel: 0.7,
      baseCooldown: 2500,
      cooldownReductionPerLevel: 30,
      baseRange: 250,
      rangePerLevel: 4,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 90,
    animationKey: 'ranger-arrow-bomb',
  },
  {
    id: 'ranger-bow-mastery',
    name: 'Bow Mastery',
    classId: CharacterClass.Ranger,
    type: SkillType.Buff,
    description: 'Activates expert bow handling, increasing accuracy and weapon attack consistency.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '🏹',
    color: '#88aa44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 8,
      mpCostPerLevel: 0.3,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'attack', baseValue: 2, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-bow-mastery',
  },
  {
    id: 'ranger-focus',
    name: 'Focus',
    classId: CharacterClass.Ranger,
    type: SkillType.Buff,
    description: 'Heightens senses to temporarily increase accuracy and avoidability. Improves movement speed.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '👁️',
    color: '#66cc88',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 6,
      mpCostPerLevel: 0.3,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'speed', baseValue: 0.2, valuePerLevel: 0.1 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-focus',
  },
  {
    id: 'ranger-arrow-rain',
    name: 'Arrow Rain',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Launches arrows high into the air, raining them down on a targeted area for devastating AoE damage.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🌧️',
    color: '#44aacc',
    scaling: {
      baseDamage: 1.5,
      damagePerLevel: 0.15,
      baseMpCost: 28,
      mpCostPerLevel: 1.0,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 60,
      baseRange: 250,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 3,
    aoeRadius: 120,
    animationKey: 'ranger-arrow-rain',
  },
  {
    id: 'ranger-strafe',
    name: 'Strafe',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Unleashes a rapid 4-arrow combo on a single target. The Ranger\'s main DPS skill at mid levels.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '⚡',
    color: '#44ff88',
    scaling: {
      baseDamage: 1.0,
      damagePerLevel: 0.10,
      baseMpCost: 22,
      mpCostPerLevel: 0.8,
      baseCooldown: 1800,
      cooldownReductionPerLevel: 25,
      baseRange: 300,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 4,
    aoeRadius: 0,
    animationKey: 'ranger-strafe',
  },
  {
    id: 'ranger-evasion-boost',
    name: 'Evasion Boost',
    classId: CharacterClass.Ranger,
    type: SkillType.Buff,
    description: 'Activates reflexive dodging, granting increased avoidability and movement speed.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '💨',
    color: '#88ff88',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 14,
      mpCostPerLevel: 0.5,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'speed', baseValue: 0.3, valuePerLevel: 0.15 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'ranger-evasion-boost',
  },
  {
    id: 'ranger-hurricane',
    name: 'Hurricane',
    classId: CharacterClass.Ranger,
    type: SkillType.Active,
    description: 'Fires arrows at extreme speed in a continuous stream. The Bow Master\'s ultimate rapid-fire technique.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '🌪️',
    color: '#22ff44',
    scaling: {
      baseDamage: 0.8,
      damagePerLevel: 0.10,
      baseMpCost: 45,
      mpCostPerLevel: 1.5,
      baseCooldown: 12000,
      cooldownReductionPerLevel: 150,
      baseRange: 320,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 8,
    aoeRadius: 0,
    animationKey: 'ranger-hurricane',
  },

  // ═══ MAGE (INT-based, AoE magic) ═══
  {
    id: 'mage-energy-bolt',
    name: 'Energy Bolt',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Fires a condensed bolt of magical energy that explodes on contact. The first attack spell Magicians learn.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '🔮',
    color: '#6644ff',
    scaling: {
      baseDamage: 1.7,
      damagePerLevel: 0.17,
      baseMpCost: 8,
      mpCostPerLevel: 0.4,
      baseCooldown: 700,
      cooldownReductionPerLevel: 10,
      baseRange: 220,
      rangePerLevel: 4,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'mage-energy-bolt',
  },
  {
    id: 'mage-fire-arrow',
    name: 'Fire Arrow',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Conjures a blazing arrow of fire that deals splash damage on impact. Ignites enemies in the blast zone.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '🔥',
    color: '#ff6622',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 15,
      mpCostPerLevel: 0.6,
      baseCooldown: 1500,
      cooldownReductionPerLevel: 20,
      baseRange: 200,
      rangePerLevel: 4,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 70,
    animationKey: 'mage-fire-arrow',
  },
  {
    id: 'mage-magic-guard',
    name: 'Magic Guard',
    classId: CharacterClass.Mage,
    type: SkillType.Buff,
    description: 'Channels mana into a protective barrier. Displaces up to 80% of incoming damage to MP instead of HP.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🛡️',
    color: '#8888ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 10,
      mpCostPerLevel: 0.4,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'defense', baseValue: 4, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-magic-guard',
  },
  {
    id: 'mage-cold-beam',
    name: 'Cold Beam',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Fires a beam of freezing ice that ignores terrain and can freeze non-resistant targets on impact.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '❄️',
    color: '#88ccff',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.16,
      baseMpCost: 16,
      mpCostPerLevel: 0.6,
      baseCooldown: 1800,
      cooldownReductionPerLevel: 25,
      baseRange: 240,
      rangePerLevel: 4,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'mage-cold-beam',
  },
  {
    id: 'mage-spell-mastery',
    name: 'Spell Mastery',
    classId: CharacterClass.Mage,
    type: SkillType.Buff,
    description: 'Activates deep magical focus, increasing magic attack and spell damage consistency for the duration.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '📖',
    color: '#aa66ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 8,
      mpCostPerLevel: 0.3,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'attack', baseValue: 3, valuePerLevel: 2.5 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-spell-mastery',
  },
  {
    id: 'mage-teleport',
    name: 'Teleport',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Instantly warps a short distance in any direction, passing through enemies. Essential Mage mobility skill.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '✨',
    color: '#cc88ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 12,
      mpCostPerLevel: 0.3,
      baseCooldown: 2000,
      cooldownReductionPerLevel: 30,
      baseRange: 150,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-teleport',
  },
  {
    id: 'mage-thunder-bolt',
    name: 'Thunder Bolt',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Calls down lightning to strike up to 6 nearby monsters. High MP cost but devastating against groups.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '⚡',
    color: '#ffff44',
    scaling: {
      baseDamage: 2.2,
      damagePerLevel: 0.22,
      baseMpCost: 30,
      mpCostPerLevel: 1.0,
      baseCooldown: 3000,
      cooldownReductionPerLevel: 40,
      baseRange: 200,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 4,
    aoeRadius: 0,
    animationKey: 'mage-thunder-bolt',
  },
  {
    id: 'mage-mp-eater',
    name: 'MP Eater',
    classId: CharacterClass.Mage,
    type: SkillType.Buff,
    description: 'Absorbs a fraction of MP from each enemy hit by magic. Temporarily boosts maximum MP pool.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '💧',
    color: '#4488ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 10,
      mpCostPerLevel: 0.4,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'maxMp', baseValue: 10, valuePerLevel: 5 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-mp-eater',
  },
  {
    id: 'mage-meteor-shower',
    name: 'Meteor Shower',
    classId: CharacterClass.Mage,
    type: SkillType.Active,
    description: 'Calls down a shower of blazing meteors from the sky, dealing massive AoE fire damage.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '☄️',
    color: '#ff4400',
    scaling: {
      baseDamage: 3.5,
      damagePerLevel: 0.30,
      baseMpCost: 45,
      mpCostPerLevel: 1.5,
      baseCooldown: 8000,
      cooldownReductionPerLevel: 100,
      baseRange: 200,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 3,
    aoeRadius: 150,
    animationKey: 'mage-meteor-shower',
  },
  {
    id: 'mage-infinity',
    name: 'Infinity',
    classId: CharacterClass.Mage,
    type: SkillType.Buff,
    description: 'Draws out unlimited mana, allowing skill use without MP cost. Increases final damage by up to 70%.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '♾️',
    color: '#aa44ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 60,
      mpCostPerLevel: 1.5,
      baseCooldown: 18000,
      cooldownReductionPerLevel: 200,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'allDamagePercent', baseValue: 20, valuePerLevel: 3 },
    buffDuration: { baseDurationMs: 30000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'mage-infinity',
  },

  // ═══ ASSASSIN (LUK-based, fast melee + thrown) ═══
  {
    id: 'assassin-lucky-seven',
    name: 'Lucky Seven',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Throws 7 lucky throwing stars at enemies ahead. Core Assassin ranged attack requiring a claw.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '⭐',
    color: '#cc44cc',
    scaling: {
      baseDamage: 1.3,
      damagePerLevel: 0.13,
      baseMpCost: 6,
      mpCostPerLevel: 0.3,
      baseCooldown: 500,
      cooldownReductionPerLevel: 8,
      baseRange: 200,
      rangePerLevel: 4,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 2,
    aoeRadius: 0,
    animationKey: 'assassin-lucky-seven',
  },
  {
    id: 'assassin-disorder',
    name: 'Disorder',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Strikes with a disorienting blow that lowers enemy defense and attack. Useful debuff before combos.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '💨',
    color: '#aa33aa',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 12,
      mpCostPerLevel: 0.5,
      baseCooldown: 1000,
      cooldownReductionPerLevel: 15,
      baseRange: 60,
      rangePerLevel: 2,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'assassin-disorder',
  },
  {
    id: 'assassin-nimble-body',
    name: 'Nimble Body',
    classId: CharacterClass.Assassin,
    type: SkillType.Buff,
    description: 'Enhances agility and reflexes, increasing movement speed and avoidability. First-job staple buff.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '🦶',
    color: '#ee88ee',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 6,
      mpCostPerLevel: 0.2,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'speed', baseValue: 0.3, valuePerLevel: 0.15 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-nimble-body',
  },
  {
    id: 'assassin-dark-sight',
    name: 'Dark Sight',
    classId: CharacterClass.Assassin,
    type: SkillType.Buff,
    description: 'Vanishes into the shadows, becoming invisible to enemies. Cannot attack while hidden, but next attack crits.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '👁️',
    color: '#442244',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 14,
      mpCostPerLevel: 0.4,
      baseCooldown: 6000,
      cooldownReductionPerLevel: 80,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'critRate', baseValue: 10, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 30000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-dark-sight',
  },
  {
    id: 'assassin-claw-mastery',
    name: 'Claw Mastery',
    classId: CharacterClass.Assassin,
    type: SkillType.Buff,
    description: 'Activates expert claw handling, increasing weapon attack and minimum damage for throwing stars.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '🗡️',
    color: '#cc88cc',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 8,
      mpCostPerLevel: 0.3,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'attack', baseValue: 2, valuePerLevel: 1.5 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-claw-mastery',
  },
  {
    id: 'assassin-haste',
    name: 'Haste',
    classId: CharacterClass.Assassin,
    type: SkillType.Buff,
    description: 'Temporarily increases movement speed and jump height for self and nearby party members.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '⚡',
    color: '#ff88ff',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 16,
      mpCostPerLevel: 0.5,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'speed', baseValue: 0.5, valuePerLevel: 0.2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-haste',
  },
  {
    id: 'assassin-savage-blow',
    name: 'Savage Blow',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Unleashes a lightning-fast 6-hit dagger combo that shreds a single target. Core melee DPS skill.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🔪',
    color: '#dd44dd',
    scaling: {
      baseDamage: 0.8,
      damagePerLevel: 0.08,
      baseMpCost: 24,
      mpCostPerLevel: 0.8,
      baseCooldown: 2000,
      cooldownReductionPerLevel: 25,
      baseRange: 50,
      rangePerLevel: 1,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 6,
    aoeRadius: 0,
    animationKey: 'assassin-savage-blow',
  },
  {
    id: 'assassin-shadow-partner',
    name: 'Shadow Partner',
    classId: CharacterClass.Assassin,
    type: SkillType.Buff,
    description: 'Summons a shadow clone that mimics your attacks at reduced damage. Effectively doubles hit count.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '👥',
    color: '#6622aa',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 30,
      mpCostPerLevel: 1.0,
      baseCooldown: 10000,
      cooldownReductionPerLevel: 120,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'allDamagePercent', baseValue: 10, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-shadow-partner',
  },
  {
    id: 'assassin-venom',
    name: 'Venom',
    classId: CharacterClass.Assassin,
    type: SkillType.Buff,
    description: 'Coats weapons in deadly poison, giving attacks a chance to inflict damage-over-time on enemies.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '☠️',
    color: '#44aa44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 14,
      mpCostPerLevel: 0.5,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'allDamagePercent', baseValue: 2, valuePerLevel: 1.5 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'assassin-venom',
  },
  {
    id: 'assassin-assassinate',
    name: 'Assassinate',
    classId: CharacterClass.Assassin,
    type: SkillType.Active,
    description: 'Charges up in the shadows then delivers a devastating single strike. Damage increases with Dark Sight buff.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '💀',
    color: '#880088',
    scaling: {
      baseDamage: 5.0,
      damagePerLevel: 0.40,
      baseMpCost: 50,
      mpCostPerLevel: 1.5,
      baseCooldown: 14000,
      cooldownReductionPerLevel: 150,
      baseRange: 55,
      rangePerLevel: 1,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'assassin-assassinate',
  },

  // ═══ PRIEST (INT-based, support + holy) ═══
  {
    id: 'priest-holy-arrow',
    name: 'Holy Arrow',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Fires a bolt of holy light. Deals bonus damage against undead monsters.',
    maxLevel: 20,
    requiredCharacterLevel: 3,
    icon: '☀️',
    color: '#ffcc44',
    scaling: {
      baseDamage: 1.6,
      damagePerLevel: 0.16,
      baseMpCost: 8,
      mpCostPerLevel: 0.4,
      baseCooldown: 800,
      cooldownReductionPerLevel: 12,
      baseRange: 200,
      rangePerLevel: 4,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 0,
    animationKey: 'priest-holy-arrow',
  },
  {
    id: 'priest-heal',
    name: 'Heal',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Restores HP to self and nearby allies. Also damages nearby undead enemies. The Cleric\'s signature skill.',
    maxLevel: 20,
    requiredCharacterLevel: 5,
    icon: '💚',
    color: '#44ff88',
    scaling: {
      baseDamage: -1.5,
      damagePerLevel: -0.15,
      baseMpCost: 20,
      mpCostPerLevel: 0.8,
      baseCooldown: 3000,
      cooldownReductionPerLevel: 40,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 120,
    animationKey: 'priest-heal',
  },
  {
    id: 'priest-bless',
    name: 'Bless',
    classId: CharacterClass.Priest,
    type: SkillType.Buff,
    description: 'Blesses self and nearby allies, increasing weapon attack, magic attack, defense and accuracy.',
    maxLevel: 20,
    requiredCharacterLevel: 2,
    icon: '✨',
    color: '#ffeeaa',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 12,
      mpCostPerLevel: 0.4,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'attack', baseValue: 2, valuePerLevel: 1 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-bless',
  },
  {
    id: 'priest-holy-symbol',
    name: 'Holy Symbol',
    classId: CharacterClass.Priest,
    type: SkillType.Buff,
    description: 'Casts a sacred symbol that boosts EXP gain and attack power for the entire party. The ultimate grinding buff.',
    maxLevel: 20,
    requiredCharacterLevel: 8,
    icon: '🔆',
    color: '#ffdd66',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 30,
      mpCostPerLevel: 1.0,
      baseCooldown: 12000,
      cooldownReductionPerLevel: 150,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'allDamagePercent', baseValue: 5, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 200,
    animationKey: 'priest-holy-symbol',
  },
  {
    id: 'priest-invincible',
    name: 'Invincible',
    classId: CharacterClass.Priest,
    type: SkillType.Buff,
    description: 'Channels holy energy to reduce incoming damage by a flat amount. Stacks with other defensive buffs.',
    maxLevel: 20,
    requiredCharacterLevel: 4,
    icon: '🛡️',
    color: '#ffcc88',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 10,
      mpCostPerLevel: 0.4,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'defense', baseValue: 4, valuePerLevel: 2.5 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-invincible',
  },
  {
    id: 'priest-divine-protection',
    name: 'Divine Protection',
    classId: CharacterClass.Priest,
    type: SkillType.Buff,
    description: 'Grants immunity to status effects and increases magic defense. Protects the party from debuffs.',
    maxLevel: 20,
    requiredCharacterLevel: 6,
    icon: '🛡️',
    color: '#ccaa66',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 12,
      mpCostPerLevel: 0.5,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'defense', baseValue: 3, valuePerLevel: 2 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-divine-protection',
  },
  {
    id: 'priest-shining-ray',
    name: 'Shining Ray',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Emits a piercing beam of holy light that damages all enemies in a line. Extra effective on undead.',
    maxLevel: 20,
    requiredCharacterLevel: 10,
    icon: '🌟',
    color: '#ffffaa',
    scaling: {
      baseDamage: 2.0,
      damagePerLevel: 0.20,
      baseMpCost: 25,
      mpCostPerLevel: 0.8,
      baseCooldown: 2500,
      cooldownReductionPerLevel: 30,
      baseRange: 250,
      rangePerLevel: 5,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 30,
    animationKey: 'priest-shining-ray',
  },
  {
    id: 'priest-dispel',
    name: 'Dispel',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Removes all abnormal status effects from allies and deals holy damage to undead in the area.',
    maxLevel: 20,
    requiredCharacterLevel: 12,
    icon: '💫',
    color: '#eedd88',
    scaling: {
      baseDamage: 1.4,
      damagePerLevel: 0.14,
      baseMpCost: 22,
      mpCostPerLevel: 0.7,
      baseCooldown: 4000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 100,
    animationKey: 'priest-dispel',
  },
  {
    id: 'priest-holy-shield',
    name: 'Holy Shield',
    classId: CharacterClass.Priest,
    type: SkillType.Buff,
    description: 'Surrounds self with a divine barrier that grants a chance to completely block incoming damage.',
    maxLevel: 20,
    requiredCharacterLevel: 15,
    icon: '✝️',
    color: '#ffee44',
    scaling: {
      baseDamage: 0,
      damagePerLevel: 0,
      baseMpCost: 18,
      mpCostPerLevel: 0.6,
      baseCooldown: 5000,
      cooldownReductionPerLevel: 50,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: { stat: 'defense', baseValue: 5, valuePerLevel: 3 },
    buffDuration: { baseDurationMs: 60000, durationPerLevelMs: 3000 },
    hitCount: 0,
    aoeRadius: 0,
    animationKey: 'priest-holy-shield',
  },
  {
    id: 'priest-genesis',
    name: 'Genesis',
    classId: CharacterClass.Priest,
    type: SkillType.Active,
    description: 'Drops pillars of holy light from the heavens, dealing massive damage to all enemies and healing allies.',
    maxLevel: 20,
    requiredCharacterLevel: 18,
    icon: '🌅',
    color: '#ffff88',
    scaling: {
      baseDamage: 3.5,
      damagePerLevel: 0.30,
      baseMpCost: 55,
      mpCostPerLevel: 1.5,
      baseCooldown: 16000,
      cooldownReductionPerLevel: 180,
      baseRange: 0,
      rangePerLevel: 0,
    },
    buffEffect: null,
    buffDuration: null,
    hitCount: 1,
    aoeRadius: 180,
    animationKey: 'priest-genesis',
  },
];

// ─── Default Key Bindings ────────────────────────

export const DEFAULT_KEY_BINDINGS: KeyBindings = {
  left: ['a', 'arrowleft'],
  right: ['d', 'arrowright'],
  up: ['w', 'arrowup'],
  down: ['s', 'arrowdown'],
  jump: [' '],
  attack: ['j'],
  skill1: ['1'],
  skill2: ['2'],
  skill3: ['3'],
  skill4: ['4'],
  skill5: ['5'],
  skill6: ['6'],
  openStats: ['p'],
  openSkills: ['o'],
  useHpPotion: ['7'],
  useMpPotion: ['8'],
  openShop: ['b'],
};

// ─── Shop Items ─────────────────────────────────

export const SHOP_ITEMS: ShopItemDefinition[] = [
  {
    id: 'shop-hp-potion',
    name: 'HP Potion',
    description: 'Restores 50 HP when used.',
    icon: '❤️',
    price: GAME_CONSTANTS.SHOP_HP_POTION_PRICE,
    type: DropType.HpPotion,
    value: GAME_CONSTANTS.HP_POTION_RESTORE,
  },
  {
    id: 'shop-mp-potion',
    name: 'MP Potion',
    description: 'Restores 30 MP when used.',
    icon: '💧',
    price: GAME_CONSTANTS.SHOP_MP_POTION_PRICE,
    type: DropType.MpPotion,
    value: GAME_CONSTANTS.MP_POTION_RESTORE,
  },
];
